### PR TITLE
ScholarX featured stories cards fix

### LINKED ISSUE #867: Change card view in scholarx
**Describe the bug**
In the Scholarx page featured stories section, there are a set of cards. Those are different from the home page cards. 

**To Reproduce**
1. Go to `ScholarX page` (from navigation-> projects-> ScholarX)
2. Scroll down to `Featured Stories` section
3. Got to `Home page`
4. Scroll down to `Our Projects` section
5. See the difference

**Expected behavior**
The `Scholarx page`,` Featured Stories` cards need to be similar(with curved edges) to the `Home page` `Our Projects` cards. 
The images on the featured stories cards need to be fitted into the new curved cards.

### PR DESCRIPTION
**Pull request by akeel230**
## Purpose
fix #867 

## Goals
make ScholarX page featured story cards look similar to Home page cards.

## Approach

1. Inspect the Home page , copy the cards settings , replace with the feature page cards
2. insert copied info from featured stories
3. Make the border round by styling
4. Fix up the padding to remove borders

### Preview Link

https://pr-1017-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
none

## Test environment
http://127.0.0.1:9000/scholarx/2021/

## Learning

- Removing and adding padding options to cards
- Removing borders

### CODE REVIEW

**Review by janethavi — CHANGES_REQUESTED** [review]
@akeel230 there is a small adjustment which you need to do. The featured stories section is dynamically created(check [data loading function](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/functions.js#L98) and [dynamic card creation function](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/index.html#L657)). So, please make sure you dont hard code the values directly on the `index.html` page. In order to fix this issue you need to do the necessary changes  to the [dynamic card creation function](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/index.html#L657).

**Comment by akeel230** [comment]
@janethavi  alright ill look into it and let you know

**Comment by akeel230** [comment]
Screenshot (140)
almost there!

**Comment by Gravewalker666** [comment]
> Screenshot (140)
> almost there!

Can we make the title left aligned? it's hard to read it this way.

**Comment by akeel230** [comment]
Screenshot (141)
better now? @Gravewalker666

**Comment by akeel230** [comment]
@Gravewalker666 center align look better for me though, anyway ur choice.

**Comment by Gravewalker666** [comment]
better but we could improve this further.

**Comment by akeel230** [comment]
@Gravewalker666  make the suggestions ill see them done with pleasure. And ill make some changes on my own too, Thanks! :)

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
image
@akeel230

**Comment by akeel230** [comment]
@Gravewalker666 thanks alot , btw take a look at this 
Screenshot (143)

**Comment by akeel230** [comment]
Screenshot (144)
@Gravewalker666 made the requested changes

**Comment by akeel230** [comment]
Screenshot (148)
@Gravewalker666 @janethavi Please take a look now

**Comment by akeel230** [comment]
Screenshot (153)
normal view
Screenshot (152)
mobile view

**Pull request closed without merging**
