### PR TITLE
Add a Tech stack session to README.md

### LINKED ISSUE #1054: Add a Tech stack session to README.md
**Is your feature request related to a problem? Please describe.**
 Improve readability of our repository’s codes https://sef.discourse.group/t/improve-readability-of-our-repositorys-codes/333

**Describe the solution you'd like**
Add a tech stack session to the README.md file and point out the technologies used in the repo's 

**Describe alternatives you've considered**
using names such as,
-site is built using
-further reading

### PR DESCRIPTION
**Pull request by akeel230**
## Purpose
Improve readability of our repository’s codes fix #1054 

## Goals
Give an idea about what technologies are used in our repositories 
https://sef.discourse.group/t/improve-readability-of-our-repositorys-codes/333/15

## Approach
Add tech stack session and add techs used along with the brief introduction 

### Preview Link

https://pr-1055-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Good job! @akeel230 Can you link the documentation as well

**Comment by akeel230** [comment]
@anjula-sack sure ill make add the documentations

**Comment by akeel230** [comment]
@anjula-sack  added official webs for Bootstrap and Jquery and added an introduction article for moustache js

**Review by anjula-sack — CHANGES_REQUESTED** [review]
I think it's better to link the name instead of adding it as a link  ex: `[bootstrap](url)`

**Comment by akeel230** [comment]
@anjula-sack alright man working on it

**Comment by akeel230** [comment]
@anjula-sack please take a look now.

**Review by anjula-sack — CHANGES_REQUESTED** [review]
`Bootstrap (https://getbootstrap.com/) ->  [Bootstrap](https://getbootstrap.com/)`
like this

**Comment by akeel230** [comment]
@anjula-sack oh! u mean make the names as links as in its clickable .. ok got it . I'll do it

**Comment by akeel230** [comment]
@anjula-sack done. Please take a look

**Review by anjula-sack — APPROVED** [review]
Thank you! @akeel230

**Pull request merged**
