### PR TITLE
Remove unwanted section from ScholarX page

### PR DESCRIPTION
**Pull request by BhathiyaTK**
## Purpose
Solved issue #319 

## Goals
Remove the unwanted section.

## Approach
Removed unwanted section tag with its sub-components.

### Screenshots
N/A
  
### Preview Link
https://bhathiyatk.github.io/sef-site/src/main/webapp/scholarx

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
N/A

## Test environment
Firefox Developer Edition v72.0b11, Google Chrome Dev v81.0.4000.3, Opera Browser v65.0.3467.78, Microsoft Edge v44.18362.449.0

## Learning
N/A

### CODE REVIEW

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
@BhathiyaTK Please change only the relevant part of the file.
Don't change the code format.

**Comment by BhathiyaTK** [comment]
@jayasanka-sack I just removed the content of the relevant section without removing the whole section. Please review.

**Comment by Piumal1999** [comment]
@BhathiyaTK There are some conflicts in your PR. Could you please resolve those conflicts and send us a PR.

**Comment by jayasanka-sack** [comment]
@BhathiyaTK Stil there are many changes in the file. 
Could you please update only the relevant section of the file. (format only the part you did)

**Comment by BhathiyaTK** [comment]
@jayasanka-sack @Piumal1999 Fixed the issue. Check this out.

**Comment by Piumal1999** [comment]
Good job! @BhathiyaTK Thank you!!

**Pull request merged**
