### PR TITLE
new button added for redirect to scholarx platform

### PR DESCRIPTION
**Pull request by kamalchakma1**
## Purpose

The purpose of this PR is to fix #<issue-number>

### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [ ] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by mayura-andrew** [comment]
@kamalchakma1 hey, can you share a screenshop what you have done here?

**Comment by mayura-andrew** [comment]
that preview link is not working right?

**Comment by kamalchakma1** [comment]
> @kamalchakma1 hey, can you share a screenshop what you have done here?

Hi, give me a minute

**Comment by kamalchakma1** [comment]
> that preview link is not working right?

yes

**Comment by kamalchakma1** [comment]
Hi, please have a look at screenshots. Button I have added is Explore ScholarX.

**Before Changes:**

before


**After Changes:**

after

**Comment by kamalchakma1** [comment]
> that preview link is not working right?

**Pull request closed without merging**
