### PR TITLE
Align headers center on the ScholarX page

### PR DESCRIPTION
**Pull request by BhathiyaTK**
## Purpose
Solve PR #400 

## Goals
Aligned requested headers to the center.

## Approach
Added `text-center` class to relevant headers.

### Screenshots
Screenshot (72)
Screenshot (73)
Screenshot (74)
  
### Preview Link
[https://bhathiyatk.github.io/sef-site/src/main/webapp/scholarx](url)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
N/A

## Test environment
Firefox Developer Edition v73.0b6, Google Chrome Dev v81.0.4021.2, Opera v66.0.3515.36, Microsoft Edge v44.18362.449.0

## Learning
N/A

### CODE REVIEW

**Comment by Piumal1999** [comment]
@BhathiyaTK
Two sections have automatically center-aligned as a result of previous PR(#401). So could you please sync your repository again and center align only the 'Mentors' heading. We are extremely sorry for the inconvenience.

**Comment by BhathiyaTK** [comment]
Okay. I will do.

**Comment by BhathiyaTK** [comment]
Done

**Comment by Piumal1999** [comment]
Well done 🤩 @BhathiyaTK 
Thanks you!!

**Pull request merged**
