### PR TITLE
Fix student list in index file

### LINKED ISSUE #639: Fix the student list in index page
**Is your feature request related to a problem?**
The student list in index file should be changed.

**Describe the solution you'd like**
Change the list by creating an extra bullet.

### PR DESCRIPTION
**Pull request by Gimhan-minion**
## Purpose
The purpose of this PR is to fix #639 

## Goals
To correct the mistake in sentences and break lines.

## Approach
<li>
                                            1 to 1 premium mentoring by industry experts and academics across the world.
                                        </li>
                                        <li>
                                            Exposure to postgraduate, internship and job opportunities. 
                                        </li>

### Screenshots
Screenshot (33)

## Preview Link
https://pr-638-sef-site.surge.sh/  

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
N/A

### CODE REVIEW

**Comment by Piumal1999** [comment]
Wow! Good job @Gimhan-minion !🤩

**Comment by Piumal1999** [comment]
And, usually you have to create an issue before sending a pull request. So could you please create an issue. It will take only few minutes.
Don't forget to mention the issue number on the pull request description.😊

**Comment by Gimhan-minion** [comment]
> And, usually you have to create an issue before sending a pull request. So could you please create an issue. It will take only few minutes.
> Don't forget to mention the issue number on the pull request description.😊

Okay!!! Thanks💙

**Review by anjula-sack — APPROVED** [review]
Awesome! @Gimhan-minion

**Review by Piumal1999 — APPROVED** [review]

**Comment by Piumal1999** [comment]
Well done @Gimhan-minion 🎉
Thanks for contributing😍

**Pull request merged**
