### PR TITLE
Remove unwanted content from the scholarx2020 archive page

### LINKED ISSUE #917: Remove unwanted content from the scholarx2020 archive page
**Describe the bug**
On the [scholarx2020 page](https://sefglobal.org/scholarx/archive/2020/), there are some unwanted content that needs to be removed.

**To Reproduce**
1. Go to [https://sefglobal.org/scholarx/archive/2020/](https://sefglobal.org/scholarx/archive/2020/)
2. Scroll down until FAQ for mentors, FAQ for mentees, Take a look at our past ScholarX and Find a mentor for me

**Expected behavior**
These entire sections need to be removed from the scholarx2020 page.
1) FAQ for mentors
2) FAQ for mentees
3) Take a look at our past ScholarX 
4) Find a mentor for me

### PR DESCRIPTION
**Pull request by gajindubandara**
## Purpose
The purpose of this PR is to fix #917

## Goals
To remove unwanted content from the scholarx2020 archive page

## Approach
Removed unwanted content from the https://sefglobal.org/scholarx/archive/2020/

### Screenshots
Screenshot from 2021-04-19 20-46-51

  
### Preview Link

https://pr-922-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gravewalker666 — APPROVED** [review]
Looks good, thank you @gajindubandara 
@janethavi do we need to keep the timelines on archive pages?

**Review by janethavi — APPROVED** [review]
Great Work @gajindubandara  💯

**Comment by janethavi** [comment]
> Looks good, thank you @gajindubandara
> @janethavi do we need to keep the timelines on archive pages?

@Gravewalker666 I didn't mention removing the timeline because in case if anybody wants to compare the past scholarx time period they have the option of doing it.

But if the above reason is not important we can remove it. WDYT?

**Comment by Gravewalker666** [comment]
> @Gravewalker666 I didn't mention removing the timeline because in case if anybody wants to compare the past scholarx time period they have the option of doing it.
> 
> But if the above reason is not important we can remove it. WDYT?

Oh yeah, that's a valid argument, users might wanna check and compare the timelines
It's alright then I guess

**Pull request merged**
