### PR TITLE
Merge onelive-events branch to master branch

### LINKED ISSUE #604: Display upcoming events within the OneLive page.
**Is your feature request related to a problem? Please describe.**
In the current site if a user wants to view the upcoming OneLive events and clicks on the "See upcoming events button" he is then redirected to Facebook.  

**Describe the solution you'd like**
It would be more convenient if we could display the upcoming events on the site itself without having to redirect to Facebook.

### PR DESCRIPTION
**Pull request by Piumal1999**
## Purpose

The purpose of this PR is to fix #604 

## Goals

Display upcoming onelive events on onelive page

## Approach

Developed on a separate branch
Merged it to the master branch
Resolved Conflicts

### Screenshots

N/A
  
### Preview Link

https://pr-671-sef-site.surge.sh/onelive
https://pr-671-sef-site.surge.sh/examples/components.html

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 
#649 #654 #670 

## Test environment
 
Ubuntu 19.04
Google Chrome

## Learning

N/A

### CODE REVIEW

**Review by jayasanka-sack — APPROVED** [review]
Thanks @Piumal1999 !
We are so fortunate to have an innovator like you on our team!


PS:
Please add the exact preview link.

**Comment by jayasanka-sack** [comment]
# 🚨Important! DO NOT SQUASH AND MERGE! 🚨

**Review by anjula-sack — APPROVED** [review]

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Btw, The preview isn't working. Could you please look int to that?

**Comment by Piumal1999** [comment]
Updated the preview link

**Comment by Piumal1999** [comment]
> Btw, The preview isn't working. Could you please look int to that?

@jayasanka-sack Currently there are no events on the calendar because the next onelive date is not confirmed yet.

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Add functions to the functions.js file

**Review by anjula-sack — CHANGES_REQUESTED** [review]
```
payload.items.forEach( item => {

    console.log(item.description);
});
```


Use this instead of this.

```
for (let i = 0; i < payload.items.length; i++) {
     
      console.log(payload.items[i].description);

}
```

**Pull request closed without merging**
