### PR TITLE
Remove the image on the second section of the Join Us page

### LINKED ISSUE #381: Remove the image on the second section of the Join Us page
**Is your feature request related to a problem? Please describe.**
Second image on the Join us page is unnecessary 

**Describe the solution you'd like**
Just remove the image and align the text to left

**Additional context**
- This is the section that needs to be changed
image

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

The purpose of this PR is to fix #381 

## Goals

- Remove the image on the second section of the Join Us page

## Approach

- Remove the image on the second section of the join_us.html page

### Screenshots

Screenshot from 2020-01-16 19-37-06

  
### Preview Link

https://pr-384-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Gravewalker666** [comment]
@jayasanka-sack Is this the way we are expecting this component to be?
Akshika Aiya didn't precisely mentioned the way the text should be after removing the image.

**Comment by jayasanka-sack** [comment]
According to #381 , the text also needs to be removed.

**Comment by jayasanka-sack** [comment]
The content moved to the header.

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Remove the whole section.

**Comment by Gravewalker666** [comment]
Oh! thank you for pointing out

**Review by jayasanka-sack — APPROVED** [review]

**Comment by jayasanka-sack** [comment]
Thanks @anjula-sack !

**Pull request merged**
