### PR TITLE
Rearrange 'Join Us' section

### LINKED ISSUE #1137: Relocate the Join the team button
**Is your feature request related to a problem? Please describe.**
The " Join the team" button has to be moved just below the volunteer description of the "At SEF, We Have Something In Store For Everyone!" section.

It is currently below the testimonial section 

**Describe the solution you'd like**

Screenshot (545)

**To fix the issue**
move the text and the join the team button below the volunteer description and above the Press coverage section.
Screenshot (546)

**Additional context**
This would further enhance the flow on the home page

### PR DESCRIPTION
**Pull request by AkshayHere**
## Purpose
Rearranged 'Join Us' section 
The purpose of this PR is to fix #1137

## Goals
Enhance the flow on the home page

## Approach
NA

### Screenshots
image
  
### Preview Link
https://pr-1140-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
NA

## Test environment
NA

## Learning
NA

### CODE REVIEW

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
Well Done!! @AkshayHere 
But there are some unwanted formatting changes in your commit. Could you please remove those and update the Pull request. Feel free to contact us if you need any help.

@akeel230 What do we do to the background colour of this section? Shall we change it to the secondary bg colour.

**Comment by AkshayHere** [comment]
Hi @Piumal1999, I have initially used 'Prettier' for formatting purposes.
I would recommend using ESLint features to make sure that the code consistency is maintained before commits.
I have updated as requested.

**Review by Piumal1999 — APPROVED** [review]
Well done! Thank you very much @AkshayHere 

> I would recommend using ESLint features to make sure that the code consistency is maintained before commits. 

Yeah we'll consider that. cc: @akeel230

**Review by gajindubandara — COMMENTED** [review]
Thank you! @AkshayHere

**Pull request merged**
