### PR TITLE
Add fade-in animation to onelive archive cards

### LINKED ISSUE #757: Add a loading animation for onelive archive cards
**Is your feature request related to a problem? Please describe.**
When the load more button on https://sefglobal.org/onelive/archive/ is clicked, the cards load instantly.

**Describe the solution you'd like**
Add a fading or any other suitable loading effect to trigger when the load more button is clicked.

Hint:
1) you can find the loading function here --> "/onelive/archive/functions.js"

2)`$(renderedHtmlContent).appendTo('#youtube-videos').hide().fadeIn(1000);`
This gets renderedHtmlContent --> appends it to youtube-videos --> Hide it --> FadeIn

also, you can refer the fading command in "loadProfiles" function in "/onelive/functions.js" file.

**Describe alternatives you've considered**
N/A

**Additional context**
Please put a comment on the issue before start working on the issue

### PR DESCRIPTION
**Pull request by nisan-abeywickrama**
## Purpose

The purpose of this PR is to fix #757 

## Goals

Solving the issue of loading the cards instantly by adding an animation

## Approach

Hiding the card and reshowing it with a fade in animation of 1.5s.

  
### Preview Link

https://pr-777-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Gravewalker666** [comment]
@nisan-abeywickrama Great Job. Thank you for contributing. 
It'll be super helpful to understand what you did and how you did it if you can fill the full PR template.
And replace the `{PR-NUMBER}` in the preview link with the pr number (777 in this PR) so that we can see your change in action.

**Comment by nisan-abeywickrama** [comment]
Done

**Review by Gravewalker666 — APPROVED** [review]
Superb! Thanks again for your valuable contribution.
Join our Gitter channel and discourse to stay updated on the issues we create throughout October, bring that awesome t-shirt home.
Gitter: https://gitter.im/sef-global/community
Discourse: http://sef.discourse.group/

**Review by Piumal1999 — APPROVED** [review]
Well done @nisan-abeywickrama !
Thanks for contributing.

**Pull request merged**
