### PR TITLE
Removed Meet Our Team section from teams page

### LINKED ISSUE #880: Removing an Unnecessary Section
**Describe the bug**
Need to remove the section shown in the screenshot from the "Team Page" as it doesn't add value and distracts the people who visit the page.

**To Reproduce**

**Expected behaviour**
Remove "Meet Our Team
Success of every organization depends on the team
and we got the "right" team" Section

**Screenshots**
image

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
This is not exactly a bug, but a removal of an extra text content

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
## Purpose

The purpose of this PR is to fix #880 .

## Goals

Removed the section from the "Team Page" as it doesn't add value and distracts the people who visit the page.

### Preview Link

https://pr-885-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by janethavi — CHANGES_REQUESTED** [review]
Great work @96RadhikaJadhav!
A small change to the PR template. Will you be able to correct the `Preview Link`?  It should be corrected to `https://pr-885-sef-site.surge.sh/`

**Review by Gimhan-minion — APPROVED** [review]
Thank you @96RadhikaJadhav Looks good to me! Please change the preview link in the description.

**Review by anjula-sack — APPROVED** [review]
Thank you! @96RadhikaJadhav

**Comment by 96RadhikaJadhav** [comment]
> Great work @96RadhikaJadhav!
> A small change to the PR template. Will you be able to correct the `Preview Link`? It should be corrected to `https://pr-885-sef-site.surge.sh/`

@janethavi  Done :)

**Review by Gimhan-minion — APPROVED** [review]

**Review by janethavi — APPROVED** [review]
Great Work @96RadhikaJadhav

**Pull request merged**
