### PR TITLE
Complete the SA page

### PR DESCRIPTION
**Pull request by jeevanthask**
a custom css has been added to the main CSS file.

### CODE REVIEW

**Comment by Piumal1999** [comment]
@jeevanthask please give us a description using the pull request template

**Comment by jeevanthask** [comment]
## Purpose
finishing the student ambassador page

## Goals
completing #291 UI

## Approach
created the basic sections using the UI

### Screenshots

  
Screenshot_2019-12-22 Student Ambassador

### Preview Link
https://jeevanthask.github.io/sef-site/src/main/webapp/SA

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
N/A

## Test environment
Google Chrome

## Learning
N/A

**Comment by Piumal1999** [comment]
Well done @jeevanthask 😍
But there's a some issues in the mobile view. Can you fix it and commit

**Comment by jeevanthask** [comment]
ok.sure !

**Comment by Piumal1999** [comment]
Good job! @jeevanthask 
And we need a few changes.

- [ ] Fix the alignment of content on "Responsibilities and specific duties" Section
- [ ] Resolve the conflicts
- [ ] Squash the commits (This article will help you.. https://github.com/wprig/wprig/wiki/How-to-squash-commits)

@jayasanka-sack need comments

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Since this file is used in other files too.. These changes may affect them as well. 
So, we need to be careful when using selectors. Use specific selectors. 
ex: do not use single selectors such as `.card-text` without a specific reason.
Try to avoid using ids. 
Use bootstrap classes as much as possible instead of writing custom CSS rules.

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
Good job so far but there are some small issues in mobile view it seems that the page is not that responsive. 
Let me point out some responsive issues.
- Responsibilities text
image
- Margin in the last section
image

I think this CSS class is the cause of the first issue
   image
I think this documentation will help you in resolving this https://getbootstrap.com/docs/4.4/utilities/display/#hiding-elements

**Comment by Piumal1999** [comment]
Closing this PR since no activity.

**Pull request closed without merging**
