### PR TITLE
Change the card view of ScholarX

### LINKED ISSUE #867: Change card view in scholarx
**Describe the bug**
In the Scholarx page featured stories section, there are a set of cards. Those are different from the home page cards. 

**To Reproduce**
1. Go to `ScholarX page` (from navigation-> projects-> ScholarX)
2. Scroll down to `Featured Stories` section
3. Got to `Home page`
4. Scroll down to `Our Projects` section
5. See the difference

**Expected behavior**
The `Scholarx page`,` Featured Stories` cards need to be similar(with curved edges) to the `Home page` `Our Projects` cards. 
The images on the featured stories cards need to be fitted into the new curved cards.

### PR DESCRIPTION
**Pull request by AlexARNcode**
## Purpose
The purpose of this PR is to fix #867

## Goals
I modified the HTML (_scholarx/2021/index.html_) and CSS (_scholarx/2021/styles.css_) to modify the look of the scholarx's page cards.

## Approach

- _scholarx/2021/index.html_ : I took the "Our Projects" section of the [home page](https://sefglobal.org/) as an example to build the new cards in HTML
- _scholarx/2021/styles.css_ : I've created several CSS classes to style the cards and their inside content : .author / .card-body / .card-text / .fa-clock .

### Screenshots
**Before** : 

before

**After** : 

Screenshot_2021-02-21 ScholarX Sustainable Education Foundation(1)

  
### Preview Link

https://pr-874-sef-site.surge.sh/

##  Checklist
- [X] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [X] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas (not needed)
- [X] I have made corresponding changes to the documentation (not needed)

## Test environment
Tested on Firefox and Chrome.

## Learning
https://www.w3schools.com/howto/howto_css_cards.asp : I used it specifically to know how to make the top of the card curved, even with the image inside.

### CODE REVIEW

**Review by janethavi — CHANGES_REQUESTED** [review]
There is a small issue with the approach you have used. These cards are created dynamically with the data. We have one template for the cards and iteratively the data is getting populated onto the cards. 

You can check the following code fragments.
[Data File](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/featured-stories.json)
[Template of the card](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/index.html#L681-L707)
[JS Script](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/functions.js#L92-L131)

**Comment by AlexARNcode** [comment]
> There is a small issue with the approach you have used. These cards are created dynamically with the data. We have one template for the cards and iteratively the data is getting populated onto the cards.
> 
> You can check the following code fragments.
> [Data File](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/featured-stories.json)
> [Template of the card](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/index.html#L681-L707)
> [JS Script](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/functions.js#L92-L131)

Hi mate,

I've looked into the actual source code of scholarx, and the data is raw for the moment, not dynamically added.

So that's why I followed the same template as the current one.

But I can give it a try in this PR if you want, I think I did understand what need to be done.

**Comment by janethavi** [comment]
Hi @AlexARNcode,
What I meant by dynamically adding is, the data that is used to populate the cards are taken from a JSON file. It's not hardcoded in the HTML file. So it's easy to add/remove any data. The JSON file which is used can be viewed from the above-mentioned links.

**Comment by AlexARNcode** [comment]
Hi @janethavi ,

I did completely understand what you were explaning.

What I meant is that currently, its actually hardcoded in the HTML file for the 2021 scholarx index page. 
I've looked at the source code of 2021 the scholarx index page and didn't  see that the cards are populated dynamically for the moment. But again, I might be completely wrong!

Anyway, I've tried to implement it but find it's not working, I think I might need help, sorry, I've tried this :
`<script type="text/html" id="template-featured-stories">
        <div class="col-10 mx-auto"> 
            <div class="card-deck px-0">
                <a href="{{url}}" target="_blank" class="card shadow project-card">
                    <div class="card-body">
                        OneLive
                        <p class="card-text text-darker text-center">
                            ScholarX Class of 2019 | SX19
                        </p>
                    </div>
                    <div class="card-footer">
                        <div class="author">
                            
                            <span>{{author.name}}</span>
                        </div>
                        <div class="stats ml-auto">
                            <i class="far fa-clock"></i> {readingTime}} min read
                        </div>
                    </div>`
                    
 This code is just for the first card, I didn't want to paste averything to keep it short.
 
 But nothing appears on the screen, I'm sure I'm doing something wrong. PS: I didn't forgot to close the <script> tag at the end ;)
 
 Sorry mate, I didn't know they would be so many things to modify when working on this issue. I'm still a beginner learning. I will think twice before taking an issue the next time, I promise :D.

**Comment by janethavi** [comment]
Hey @AlexARNcode,
It's really good if we can learn something new every day. We always develop our skills by making mistakes and correcting them on the go. So 1st let me explain how the code currently works. And I will give you a hint about how you can apply your solution for this code.

**Previously in this thread I mentioned all the links which are directly used for your solution. It would be great if you can have a look into that 1st. I will use those words to explain the code for you.**

1) In the Data file we have 3 JSON objects from which we are dynamically creating the cards.
2) What you need to adjust is the Template of the card code fragment. 
3) In the JS Script we bind the data which was taken from the Data file(JSON file) to an object array. This array is called `data` in the code. 
4) Now we have 3 JSON objects in the `data` array. So we iteratively add these data to the Template of the card. So we have now dynamically created 3 cards. [View data array from this link](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/index.html#L683)

**Something extra to understand:- For testing purposes, you can add a sample data object to the Data file and you will see that there are 4 cards created now. We haven't edited the HTML but we have only added new data to the Data file.** 

So for your solution, you need to edit the `Template of the card code`.

Okay now to answer your question.
As I can see in the code you have attached, the array `data` is missing. That may be the reason you don't see anything on your screen. you have missed the [data](https://github.com/sef-global/sef-site/blob/master/scholarx/2021/index.html#L683) array

**Comment by AlexARNcode** [comment]
Hi @janethavi,

Thanks a lot for your patience and for explaining everything to me, I really appreciate.

I did already understand most of it, but it's in applying it and making it work that I had a problem. So I'm going to follow your advice on the data array.

I'll work on that this weekend, as I'm now following a 6 months intensive web development course.

Thanks a lot a gain.

**Comment by Gimhan-minion** [comment]
@janethavi Could you please look into this PR.

**Comment by janethavi** [comment]
Hey @Gimhan-minion the approach used in this fix is wrong. @AlexARNcode has removed the dynamic loading of the cards. In this fix, @AlexARNcode has changed the content to static. We haven't heard from @AlexARNcode for a long time too.

**Comment by Gimhan-minion** [comment]
I'll close this PR for now. No point in hanging this around. Thank you @janethavi 💯

**Pull request closed without merging**
