### PR TITLE
Update teams page

### LINKED ISSUE #889: Update Team Page
**Is your feature request related to a problem? Please describe.**
Team Page Needs to be updated as it is outdated. 

**Describe the solution you'd like**
1. Move retired volunteers to the Alumni Section
2. Add the latest volunteers to the Team page.

**Describe alternatives you've considered**
N/A

**Additional context**
This Issue needs more information to complete. Therefore, the person who works on this has to communicate with the management team to get information.

### PR DESCRIPTION
**Pull request by janethavi**
## Purpose
The following changes were made to the teams page.
1) New candidates were added to the teams page.
2) Design section was temporarily removed but the JSON tags were kept for future additions.
3) Consultants section was removed and the people to the external contributors section.

The purpose of this PR is to fix #889 

## Goals
Update the teams page

## Approach
N/A

### Screenshots
N/A
  
### Preview Link
https://pr-892-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Ubuntu 20.04, Chrome

### CODE REVIEW

**Comment by akshika47** [comment]
Hi, @janethavi Thank you for the PR! There is a minor change in the order of people in the Executive Committee.

Ranojaan Mahendran and Dharana Jayawardena should come to 4th and 5th places within that section and then followed by the rest of the ScholarX team members. 

The rest looks good.

@anjula-sack could you please do a review on the formatting of the code?

**Comment by janethavi** [comment]
> Hi, @janethavi Thank you for the PR! There is a minor change in the order of people in the Executive Committee.
> 
> Ranojaan Mahendran and Dharana Jayawardena should come to 4th and 5th places within that section and then followed by the rest of the ScholarX team members.
> 
> The rest looks good.
> 
> @anjula-sack could you please do a review on the formatting of the code?

Sure @akshika47 . Will fix that.

**Review by Gimhan-minion — APPROVED** [review]
Thank you @janethavi Good job 💯

**Review by anjula-sack — APPROVED** [review]
Thank you! @janethavi

**Pull request merged**
