### PR TITLE
Add section to collect more success stories for scholarx-success-stories page

### LINKED ISSUE #1344: Add a form to collect more stories for scholarx-success-stories page
**Is your feature request related to a problem? Please describe.**
We need to add a form to the ScholarX Success stories page to get more stories from the past mentees.

**Describe the solution you'd like**
Add a new section to the Scholarx-success-stories page which direct users to a google form where we can collect responses.

**Describe alternatives you've considered**
None

**Additional context**
[Hive post](https://sef.discourse.group/t/scholarx-success-stories-page/420/33?u=madhawa)

**Are you working on it?**
Yes. Assign me please.

### PR DESCRIPTION
**Pull request by Madhawa97**
## Purpose

The purpose of this PR is to fix #1344 

## Goals
To add a form to the ScholarX Success stories page to get more stories from the past mentees.

## Approach
Add a new section to the Scholarx-success-stories page which direct users to a google form where we can collect responses.

### Screenshots
Screenshot 2022-10-18 at 01 21 41
  
### Preview Link

https://pr-1345-sef-site.surge.sh/scholarx/success-stories/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
macOS latest, Chrome latest

### CODE REVIEW

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Shall we add a bg for the section to make it diferentiate?

**Comment by Madhawa97** [comment]
> Shall we add a bg for the section to make it diferentiate?

I thought about it @anjula-sack. I think its best not to add the grey color that we usually add here. Because then this may seem like a part of the footer. 
Do we have any other colors? that can be used in this case.

**Comment by Madhawa97** [comment]
How about adding a light color from following image?
Screenshot 2022-10-18 at 15 54 28

**Comment by anjula-sack** [comment]
> > Shall we add a bg for the section to make it diferentiate?
> 
> I thought about it @anjula-sack. I think its best not to add the grey color that we usually add here. Because then this may seem like a part of the footer. Do we have any other colors? that can be used in this case.

I was thinking about this color `#f8fdff`

**Comment by Madhawa97** [comment]
Yes @anjula-sack #f8fdff looks good.

**Review by Madhawa97 — COMMENTED** [review]
Hope it looks good now. Let me know if any concerns

**Comment by anjula-sack** [comment]
> Hope it looks good now. Let me know if any concerns

I think it's better without a bg color now. xD Since that section is small and the footer section is big it feels weird. can we revert it back? Sorry for the trouble. @Madhawa97

**Comment by Madhawa97** [comment]
No worries @anjula-sack. It always a pleasure!

**Comment by Madhawa97** [comment]
I prefer having some extra paddings with the white bg;
Screenshot 2022-10-19 at 16 25 19

Compared to what it was before;
Screenshot 2022-10-19 at 16 31 41

And if you're curious this is how it looks with the `#f8fdff`;
Screenshot 2022-10-19 at 16 27 15

**Comment by Madhawa97** [comment]
@anjula-sack Made a commit removing a bg color and including some padding. Let me know if it works.

**Review by anjula-sack — APPROVED** [review]
Looks awesome! @Madhawa97 Thank you!

**Comment by Madhawa97** [comment]
No problemo @anjula-sack

**Pull request merged**
