### PR TITLE
Use a google sheet to the Onelive page instead of JSON file 

### LINKED ISSUE #984: Use a google sheet to the Onelive page instead of JSON file
**Is your feature request related to a problem? Please describe.**
Currently, the Onelive page is using a  JSON file (speakers.json) to import data to the Onelive webpage. It's more efficient to use a google sheet to update the data than using a JSON file. 

**Describe the solution you'd like**
1. Instead of using the JSON file, create a new google sheet and add the data into the sheet 
2. Create a google script to export the data as a URL 
3. Use the URL  to import data from the sheet to the web page

### PR DESCRIPTION
**Pull request by gajindubandara**
## Purpose
The purpose of this PR is to fix #984

## Goals
To replace the onelive/speakers.json file with a google sheet

## Approach
* Created a google sheet and entered the data into that
    Sheet link - https://docs.google.com/spreadsheets/d/1XQI7aOokHIzbpoA5cyC5xum7EJA3tv599QUNds-d6HQ/edit?usp=sharing
* Created a google script code to export data  as a URL 
* Used the URL in the  onelive/functions.js to import the data to the page

### Screenshots

Screenshot from 2021-06-28 14-20-24

  
### Preview Link

https://pr-985-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
Looking good @gajindubandara
Can you please change the commit message into imperative to get this merged?
and try to describe which json file you replaced this with, as in now the commit message says it replaces a json file in onelive but as to which file exactly is not specified.

**Comment by gajindubandara** [comment]
> Looking good @gajindubandara
> Can you please change the commit message into imperative to get this merged?
> and try to describe which json file you replaced this with, as in now the commit message says it replaces a json file in onelive but as to which file exactly is not specified.

Yeah! I'll do it. I created the issue and this PR for the google sheet thing and the image hosting thing. But as the image hosting thing is not confirmed yet I'll remove the image hosting part from this PR and the issue

**Comment by gajindubandara** [comment]
@Gravewalker666  I  removed the image hosting part and changed the commit message

**Comment by Gravewalker666** [comment]
@gajindubandara If you think having them on google photos is convenient it's alright but make sure to give sef Gmail account access to those folders

**Comment by Gravewalker666** [comment]
@gajindubandara 
Please use imperative mood on the commit message 
Ref: https://chris.beams.io/posts/git-commit/

**Comment by gajindubandara** [comment]
> @gajindubandara If you think having them on google photos is convenient it's alright but make sure to give sef Gmail account access to those folders

I haven't used the google photos service in this PR, images are loading from the sef-site repository. Also, I gave access to the SEF Gmail account

**Comment by Gravewalker666** [comment]
> > @gajindubandara If you think having them on google photos is convenient it's alright but make sure to give sef Gmail account access to those folders
> 
> I haven't used the google photos service in this PR, images are loading from the sef-site repository. Also, I gave access to the SEF Gmail account

Alright nice

**Review by Gravewalker666 — APPROVED** [review]
nice work @gajindubandara 
really impressed, well done

**Pull request merged**
