### PR TITLE
Add testimonial section to upspeak page

### LINKED ISSUE #1038: Add a Testimonial section to the UpSpeak page
**Is your feature request related to a problem? Please describe.**
Add a testimonial section to the upspeak page

**Describe the solution you'd like**

Create the testimonial section as in the below image

Screenshot from 2021-07-22 12-06-40

Content - https://docs.google.com/document/d/1Y-Hp0zPjchSV5qHSRAIwtWsca1tpwTJs3tAgn5r2fdk/edit

### PR DESCRIPTION
**Pull request by gajindubandara**
## Purpose

The purpose of this PR is to fix #1038

## Goals
To add a testimonial section to the UpSpeak page 

## Approach
Added the testimonial section to the UpSpeak page
Did further discussions about the testimonial section in HIVE(https://sef.discourse.group/t/creating-a-new-webpage-for-upspeak/298/6?u=gajindu_bandara)

### Screenshots
Screenshot from 2021-07-22 12-29-33

  
### Preview Link

https://pr-1039-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
The code is alright, but there are a bunch of unnecessary indentation changes.
Try to keep only the changes related to the task, if it's hard to undo it's alright, there's no harm in merging this. 
Give it a try and let me know. :)

**Comment by gajindubandara** [comment]
> The code is alright, but there are a bunch of unnecessary indentation changes.
> Try to keep only the changes related to the task, if it's hard to undo it's alright, there's no harm in merging this.
> Give it a try and let me know. :)

I guess the thing is I used the code reformat function in the intel ij to make the new code in the correct order. So it has affected the whole code.

**Comment by gajindubandara** [comment]
@Gravewalker666 I tried but it seems hard to re-align all the things :sweat_smile:

**Review by Gravewalker666 — APPROVED** [review]
Oh sorry, @gajindubandara I forgot about this PR 
I thought I merged it sorry for the delay

**Pull request merged**
