### PR TITLE
Remove AcadeMix from site temporarily

### LINKED ISSUE #853: Remove AcadeMix from site temporarily
**Describe the bug**
AcadeMix page access needs to be removed temporarily from the following places.
1) In the navigation bar under projects, remove AcadeMix item with its link.
2) In the Index page remove the AcadeMix card under the projects section.
3) In the Index page under `At SEF, We Have Something In Store For Everyone!` section remove the link of `AcadeMix` word in the Student section.

### PR DESCRIPTION
**Pull request by gajindubandara**
## Purpose
The purpose of this PR is to fix #853

## Goals
To remove AcadeMix from the site temporarily

## Approach
Removed AcadeMix item and the link from the navigation bar, AcadeMix card under the projects section, and the link for AcadeMix in the student's section

### Screenshots

  
Screenshot from 2021-02-07 16-41-13
Screenshot from 2021-02-07 16-40-20

Screenshot from 2021-02-07 16-40-24

### Preview Link

https://pr-855-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gimhan-minion — APPROVED** [review]
Thank you @gajindubandara Good Job 💯 

PS:- @janethavi WDYT about the card alignment?

**Review by janethavi — CHANGES_REQUESTED** [review]
Great work @gajindubandara! 💯 
Will you be able to correct the preview link? There is a small spelling mistake there.

**Comment by janethavi** [comment]
> Thank you @gajindubandara Good Job 💯
> 
> PS:- @janethavi WDYT about the card alignment?

@Gimhan-minion Do you think we should left align the card?

**Comment by Gimhan-minion** [comment]
> > Thank you @gajindubandara Good Job 100
> > PS:- @janethavi WDYT about the card alignment?
> 
> @Gimhan-minion Do you think we should left-align the card?

Yeah, my opinion is to left-align this. @gajindubandara Can you create a new thread on the hive and get the feedback from others too?

**Comment by janethavi** [comment]
> > > Thank you @gajindubandara Good Job 100
> > > PS:- @janethavi WDYT about the card alignment?
> > 
> > 
> > @Gimhan-minion Do you think we should left-align the card?
> 
> Yeah, my opinion is to left-align this. @gajindubandara Can you create a new thread on the hive and get the feedback from others too?

Yes @Gimhan-minion, we'll get others' opinion too.

**Comment by gajindubandara** [comment]
> Great work @gajindubandara! 💯
> Will you be able to correct the preview link? There is a small spelling mistake there.
Ok, I'll do it

**Comment by gajindubandara** [comment]
> > > Thank you @gajindubandara Good Job 100
> > > PS:- @janethavi WDYT about the card alignment?
> > 
> > 
> > @Gimhan-minion Do you think we should left-align the card?
> 
> Yeah, my opinion is to left-align this. @gajindubandara Can you create a new thread on the hive and get the feedback from others too?

**Comment by gajindubandara** [comment]
> > > Thank you @gajindubandara Good Job 100
> > > PS:- @janethavi WDYT about the card alignment?
> > 
> > 
> > @Gimhan-minion Do you think we should left-align the card?
> 
> Yeah, my opinion is to left-align this. @gajindubandara Can you create a new thread on the hive and get the feedback from others too?
Ok!

**Review by janethavi — APPROVED** [review]
Great Work @gajindubandara  :100:

**Pull request merged**
