### PR TITLE
Make discourse icon  look similar to other icons in navbar

### LINKED ISSUE #1308: Make discourse icon look similar to other icons in navbar
**Is your feature request related to a problem? Please describe.**
The discourse icon in the navbar does not look similar to other icons because the discourse icon's background colour should be the colour of the discourse icon's color and the background colour should be white colour.

**Describe the solution you'd like**
Make changes to css file by changing colour code.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by VishwaAmarasinghe**
## Purpose

The purpose of this PR is to fix #1308 

## Goals

To make the discourse icon look similar to other icons in the navbar.

## Approach

Changed the CSS file by changing the colour codes of this icon.

### Screenshots

image
image

  
### Preview Link

https://pr-1312-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Piumal1999 — COMMENTED** [review]
Changing the global CSS may affect some other icons on the site as well. 

By the way, using the `btn-primary` class instead of `btn-neutral` fixes this issue.
image

**Comment by VishwaAmarasinghe** [comment]
Ok

**Review by anjula-sack — APPROVED** [review]
Thank you! @VishwaAmarasinghe

**Comment by YoshithaRathnayake** [comment]
sorry mistake

**Pull request merged**
