### PR TITLE
fixed issues of photo size in team page

### LINKED ISSUE #355: Photos of design team are smaller than others
**Describe the bug**
Photos of the design team is smaller than the default size in team page

**To Reproduce**
1. Go to 'https://sef-global.github.io/sef-site/src/main/webapp/team'
2. Scroll down to 'Design team' section
3. See error

**Expected behavior**
All images having same size

**Screenshots**
Sustainable_Education_Foundation_-_2020-01-10_19 41 13

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Google Chrome

**Additional context**
Mobile view is okay.

### PR DESCRIPTION
**Pull request by yohanym95**
## Purpose

The purpose of this PR is to fix #355 

## Goals

Fixed issue of photos in design team
## Approach

Apply CSS styles for photo component.(img tag)

### Screenshots

ssss
  
### Preview Link

https://yohanym95.github.io/sef-site/src/main/webapp/team.html

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
Windows 10, Google Chrome

## Learning

N/A

### CODE REVIEW

**Comment by Gravewalker666** [comment]
Good Job!! @yohanym95

**Comment by jayasanka-sack** [comment]
I guess this isn't the expected change. Now all the profile images are bigger than the original component.
@Piumal1999 Isn't it?

@Gravewalker666 Just compare with 
https://pr-377-sef-site.surge.sh/team.html

**Comment by Gravewalker666** [comment]
@jayasanka-sack Yeah, It's a bit bigger. Sorry I didn't notice that.
@yohanym95 Can you please do necessary changes to make it a bit smaller?

**Comment by jayasanka-sack** [comment]
@Gravewalker666 Please revert the PR

**Pull request merged**
