### PR TITLE
Update README logo : assets/img/logos/readme.png

### LINKED ISSUE #857: Change README logo
**Describe the bug**
In the home page, press coverage section the readme press coverage logo needs to be updated. Replace the existing logo with the new logo.

**To Reproduce**
1. Go to 'https://sefglobal.org/'
2. Scroll down to 'Press Coverage'
3. See old logo of `Readme`

**Expected behavior**
The new logo needs to be added. Adjust the size of the new logo to match the rest of the logos on the home page. The new logo should not affect the consistency look with the rest of the logos.
107512208_3369757173073130_4804089304883641529_o

### PR DESCRIPTION
**Pull request by AlexARNcode**
## Purpose
The purpose of this PR is to fix #857 .

## Goals
This PR will use the new logo provided in https://github.com/sef-global/sef-site/issues/857 (direct link to the new logo: https://user-images.githubusercontent.com/35697678/107602390-4aea0900-6c4f-11eb-9384-f4c8afa97d4c.png).

It will replace the old logo with this new one in the folder assets/img/logos .

## Approach
I've resized the given logo so that it fits the same ratio and height of the other logos.

Then I replaced the old readme.png logo with the new one, erasing the old one.

I didn't modify any HTML, since it's not necessary in that case (the file having the same name readme.png)

### Screenshots
**Before :** 
sef-site-readme-before png

**After :**
sef-site-readme-update

  
### Preview Link

https://pr-859-sef-site.surge.sh/

##  Checklist
- [X] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [X] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (not needed)
- [ ] I have made corresponding changes to the documentation (not needed)

## Test environment
Tested on :
- Firefox
- Safari
- Chrome

## Learning
I've used GIMP to resize the provided logo and makes it fit the other ones.
I've made sure the ratio is respected, while having the same height of the other ones.

### CODE REVIEW

**Review by janethavi — CHANGES_REQUESTED** [review]
Great Work @AlexARNcode! Clean PR 💯 
A small change needs to be done in the PR `Preview Link` section
Please change the `{PR_NUMBER}` to 859(your PR number) so the link will look like https://pr-859-sef-site.surge.sh/

**Comment by AlexARNcode** [comment]
> Great Work @AlexARNcode! Clean PR 💯
> A small change needs to be done in the PR `Preview Link` section
> Please change the `{PR_NUMBER}` to 859(your PR number) so the link will look like https://pr-859-sef-site.surge.sh/

Oops, forgot that :)!
Thanks for your positive feedback @janethavi !

**Review by janethavi — APPROVED** [review]
Thank you for your contribution @AlexARNcode.

**Review by anjula-sack — APPROVED** [review]
Thank you! @AlexARNcode

**Pull request merged**
