### PR TITLE
Replace SEF gitter Channel with SEF Slack channel 

### PR DESCRIPTION
**Pull request by akeel230**
## Purpose
To lead developers into the active community platform. #986 

## Goals
Replacing the SEF Gitter  link with SEF slack link to lead people to active slack channel.

## Approach
made changes in the CONTRIBUTING.md file

##  Checklist
- [X] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [X] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Good job! @akeel230 I think S in slack needs to be capital
Can you please update the preview link and change the commit message and pr title to be in the imperative mood?
ref: https://chris.beams.io/posts/git-commit/#imperative

**Comment by anjula-sack** [comment]
The purpose should be like this `The purpose of this PR is to fix #986` and you don't need to add the issue number in the PR title

**Comment by akeel230** [comment]
@anjula-sack Alright ill make the changes you requested and change the commit. And also thanks! for the tip regarding the use of Purpose and PR title

**Comment by akeel230** [comment]
Made the changes that were Requested @anjula-sack , Please let me know if there anything else needs changes.

**Comment by anjula-sack** [comment]
it should be Replace not in the past tense. The same goes for the commit message as well. and also It's better to squash the commit and make it a single commit

**Comment by akeel230** [comment]
@anjula-sack 
*changed the tense of title
*changed the tense of commit 
*Sqaushed all commits into one

**Review by anjula-sack — APPROVED** [review]
Thank you! @akeel230

**Pull request merged**
