### PR TITLE
fixed some alignment issues in main div

### LINKED ISSUE #1175: Homepage content is not aligned properly in the mobile view
**Is your feature request related to a problem? Please describe.**
The first impression may not be a good one as the main section is not well aligned when someone browses this website using their mobile phone 

**Describe the solution you'd like**
Make it center-aligned as other sections for mobile devices

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by sathmikaDev**
## Purpose
The purpose of this PR is to fix #1175 
## Goals

- To make a good first impression with well-aligned(responsive ) main section

### Screenshots
Screenshot 2022-03-16 212657

##  Checklist
- [ x ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ x ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by gajindubandara — CHANGES_REQUESTED** [review]
Good job @Sathmikasenadheera01! :100: 
Can you please send the PR including only the new changes? Don't reformat the entire code.

**Comment by jayasanka-sack** [comment]
@anjula-sack @gajindubandara I think we can resolve these formatting issues by using a tool like, prettier. 

WDYT?

**Comment by sathmikaDev** [comment]
Hello,

Sorry for the late reply.
Here I'm not talking about code format or something like that.
On large screens, main section's heading and other stuff aligned to left
and on mobile devices it didn't aligned center as same as other sections.

Thanks & Regards

**Comment by Piumal1999** [comment]
Hi @Sathmikasenadheera01, Thanks for the reply. 
The design you suggested looks better than the existing one. But we couldn't merge it because there were some unwanted formatting changes. So could you please update the pull request to include only the changes you did?

Later we'll implement a mechanism to maintain a consistent code formatting structure as suggested in https://sef.discourse.group/t/creating-issues-for-upcoming-hacktoberfest/432/2

**Comment by sathmikaDev** [comment]
Sure, will do that.

**Pull request closed without merging**
