### PR TITLE
Updating Apply button to say Apply Now

### LINKED ISSUE #773: Update Onelive "Apply" button to "Apply Now"
**Is your feature request related to a problem? Please describe.**
The "Apply" button on "Be a onelive speaker" section on onelive page (sef-site/src/main/webapp/onelive/index.html) have to be changed to "Apply Now" 

IMG_20201001_234134

**Describe the solution you'd like**
Update the button text

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by yashgajaria**
## Purpose

The purpose of this PR is to fix #773 

## Goals

Update the button to say Apply Now instead of Apply

## Approach

Followed file path to locate where the change was needed and looked in the file to see where the label of the button was. 

### Screenshots

image

  
### Preview Link

https://pr-774-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Test environment
 
Tested on the preview link in Chrome and Firefox in Linux and Windows.

### CODE REVIEW

**Comment by Piumal1999** [comment]
Good job!!!😍😍😍 @yashgajaria 
Hope you'll contribute to our repos in future.
Btw, could you please fill the pull request template before we merge it?

**Comment by yashgajaria** [comment]
The template has been filled out! Thanks :)

**Review by Piumal1999 — APPROVED** [review]

**Comment by Piumal1999** [comment]
I have approved your Pull request. It will be merged after getting another approval review. 

@yashgajaria Thanks for contributing. Join our discourse and gitter community.
https://gitter.im/sef-global
https://sef.discourse.group

**Review by Gravewalker666 — APPROVED** [review]
@yashgajaria Brilliant, Thank you for contributing. 
Keep your eye on the issues tab, we'll be putting some more issues, bring home that awesome t-shirt wink... wink...
Join our chat groups and discourse to find more issues to work with.

**Pull request merged**
