### PR TITLE
Change the Web Page Titles

### LINKED ISSUE #507: Change the Web Page Titles
## Detailed Description
Existing page titles are not much meaningful. I suggest having more meaningful titles with a pattern. Changing page titles with a pattern will help to see the pages more understandable, even when found on search engines.

## Context

* Support SEO
* Give a meaningful and quick idea to visitors
* Give the website a more professional look

## Possible Implementation

* Changing titles to something with an extension.
Ex: {page_name} | Sustainable Education Foundation

## Your Environment

* Browser Name and version: Google Chrome
* Operating System and version (desktop or mobile): Windows Desktop and Android Mobile

### PR DESCRIPTION
**Pull request by nimeshkasun**
## Purpose
Addressing issue : fix #507 
Change the title of the home page, OneLive, ScholarX, IRC, SA, Meet Our Team, Join US pages

## Goals
Changing the page titles to a more meaningful titles

## Approach
Change the following page titles:
* SEF site >Home | Sustainable Education Foundation
* SEF site > OneLive | Sustainable Education Foundation
* Sustainable Education Foundation > ScholarX | Sustainable Education Foundation
* Sustainable Education Foundation > IRC | Sustainable Education Foundation
* Student Ambassador > Student Ambassador | Sustainable Education Foundation
* Sustainable Education Foundation > Meet Our Team | Sustainable Education Foundation
* Join Us > Join Us | Sustainable Education Foundation

### Preview Link

https://pr-506-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
N/A

## Test environment
Google Chrome

## Learning
N/A

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
Thanks for pointing this out @nimeshkasun !
Could you please create an issue and link with this PR?

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Thanks for pointing this out @nimeshkasun !
Could you please create an issue and link with this PR?

**Comment by nimeshkasun** [comment]
@jayasanka-sack yes I'll create an issue and link it here

**Comment by nimeshkasun** [comment]
@jayasanka-sack Issue created as requested.

**Review by jayasanka-sack — APPROVED** [review]
Thanks, @nimeshkasun !

**Pull request merged**
