### PR TITLE
Link Explore button to our projects

### LINKED ISSUE #726: Link "Explore" button to "Our Projects" section
**Is your feature request related to a problem?**
We should link "Explore" button in the landing page to "Our projects" section.

**Describe the solution you'd like**
Edit the required code lines

### PR DESCRIPTION
**Pull request by Gimhan-minion**
## Purpose
The purpose of this PR is to fix #726 

## Goals
To link "explore" button to our projects section

## Approach
Made the required changes in the code
  
### Preview Link

https://pr-727-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
Good job! @Gimhan-minion

**Review by Piumal1999 — APPROVED** [review]

**Review by anjula-sack — APPROVED** [review]
There's a conflict @Gimhan-minion

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Resolve the conflict

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
@Gimhan-minion change the link on the footer also

**Review by anjula-sack — APPROVED** [review]

**Review by Piumal1999 — APPROVED** [review]
Well done!! Thanks @Gimhan-minion

**Pull request merged**
