### PR TITLE
Create a separate project card for project Upspeak.

### LINKED ISSUE #1117: Make the Upspeak card for our projects session in the Home page
**Is your feature request related to a problem? Please describe.**
Create the upspeak card and add the information in the card

**Describe the solution you'd like**

Screenshot (474)

**Describe alternatives you've considered**
To fix the issue go to index.html file , find the our projects section , create the card following the same design 

**Additional Info**
Will have to get the information needed from the responsible parties

### PR DESCRIPTION
**Pull request by pasindur99**
## Purpose

We need a separate project card to display the upspeak project In the projects section of sef-site.
The purpose of this PR is to fix #1117

## Goals

Create a separate project card for project Upspeak.

## Approach

1. Create a separate project card.
2. Added upspeak image. (The image height was not fit with the other images. Because of that, I created a CSS class with default image height for the project card images).
3. Added dummy detail until the required details will be gathered.

### Screenshots

image

  
### Preview Link

https://pr-1122-sef-site.surge.sh/

##  Checklist
- [X] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [X] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
macOS
Google chrome

### CODE REVIEW

**Comment by pasindur99** [comment]
The pr converted to draft because I added dummy detail until the required details will be gathered. Thank you.

**Comment by akshika47** [comment]
Design-wise it looks good. Please do come up with a sample text so we can review it.

I also suggest changing the order of events.

ScholarX -> IRC -> OneLive -> Academix -> UpSpeak -> SA (same should go for drop down-lists as well, maybe this could be another issue)

**Comment by janethavi** [comment]
> Design-wise it looks good. Please do come up with a sample text so we can review it.
> 
> I also suggest changing the order of events.
> 
> ScholarX -> IRC -> OneLive -> Academix -> UpSpeak -> SA (same should go for drop down-lists as well, maybe this could be another issue)

Created a separate issue for the card reordering https://github.com/sef-global/sef-site/issues/1123

**Comment by pasindur99** [comment]
Okay, @akshika47 . I will update the pr by adding some sample text.

**Comment by pasindur99** [comment]
Added details provided by Minuri.
Please review the pr.

## Screenshot
image

**Comment by akeel230** [comment]
@pasindur99 the upspeak logo looks a bit stretched vertically can u fix that, please?

**Comment by pasindur99** [comment]
Fixed with b290ed0
image

**Review by jayasanka-sack — DISMISSED** [review]
The logo looks misaligned compared to the Academix logo. (probably because of the letter “p”)  In that case, let’s get this merged. We could create a separate issue to align it properly. Having the data on the site is the priority.

Anyway, looks good to me. Thanks, @pasindur99! Good job as always!

**Review by Piumal1999 — COMMENTED** [review]
@jayasanka-sack @akeel230, Does the number match with the text below it? 
The number of students is 9,  but the text says "Improved English speaking skills"

**Comment by pasindur99** [comment]
@Piumal1999 That was minuri's inputs. I think the idea behind that was "Nine students improved English speaking skills" through the project until now.

**Comment by pasindur99** [comment]
Fixed with https://github.com/sef-global/sef-site/pull/1122/commits/0fad954519cb14e708fd2790d52639be8b7d1688
image

**Comment by pasindur99** [comment]
Fixed. 
image

@jayasanka-sack @Piumal1999

**Review by jayasanka-sack — APPROVED** [review]
Thanks for getting this done, @pasindur99 !

**Pull request merged**
