### PR TITLE
Add mentee table

### LINKED ISSUE #919: Create a table for 2019 scholarx mentees
**Is your feature request related to a problem? Please describe.**
In the archive section of scholarx2019 a table needs to be created to add the mentees to the website.

**Describe the solution you'd like**
The table should contain an image, name, mentor and the university or a single mentee. When clicked on a single mentee the LinkedIn profile should be redirected. The data file can be found [here](https://docs.google.com/spreadsheets/d/1UquBXrpWIxdLdy5vOeflvtaKUgv6z-GhVMLK-g44gPU/edit#gid=0)

### PR DESCRIPTION
**Pull request by janethavi**
## Purpose
The purpose of this PR is to fix #919
Added the mentee table for scholarx 2019.

## Goals
View all the past mentees.

## Approach
Used bootstrap table.

### Screenshots
Screenshot from 2021-04-18 23-48-05

  
### Preview Link

https://pr-920-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Ubuntu 20.04 Chrome

### CODE REVIEW

**Review by anjula-sack — COMMENTED** [review]
Can we use a placeholder image for those who don't have images? @janethavi

**Comment by janethavi** [comment]
> Can we use a placeholder image for those who don't have images? @janethavi

Sure I will add it!

**Review by anjula-sack — APPROVED** [review]
Good job! @janethavi

**Comment by akshika47** [comment]
Good job @janethavi . Few minor changes on this.

1. It is not Tharindu Jayathilaka, it is - https://www.linkedin.com/in/tarinduj/
2. Keep things consistent: 
- please use the two names of the mentors and mentors
- Only keep the University name [E.g.: remove SurfEdge (PVT) Ltd from Adhisha]
- Montana State University-Bozeman,USA [keep a space before the 'USA'] -> Montana State University-Bozeman, USA 
- Sabaragamuwa University Of Srilanka [keep space between Sri and Lanka and make the L capital and add 'the'] -> The Sabaragamuwa University Of Sri Lanka
- Above are some examples please everything for consistency.
3. Savithru Jayasinghe is Dr as well during the time of this mentor program.
4. Missing people links and use their headshots from LinkedIn : 

- https://www.linkedin.com/in/janidu-jayasanka-36435a145/
- https://www.linkedin.com/in/ramithhettiarachchi/
- https://www.linkedin.com/in/matheesha-abeysekera/
- https://www.linkedin.com/in/najma-azmy-553928134/
- https://www.linkedin.com/in/insaf-ismath-59b213138/ [change IM Insaf to Insaf Ismath]
5. Remove the heading "image" -> It doesn't add much value

**Comment by janethavi** [comment]
> Good job @janethavi . Few minor changes on this.
> 
> 1. It is not Tharindu Jayathilaka, it is - https://www.linkedin.com/in/tarinduj/
> 2. Keep things consistent:
> 
> * please use the two names of the mentors and mentors
> * Only keep the University name [E.g.: remove SurfEdge (PVT) Ltd from Adhisha]
> * Montana State University-Bozeman,USA [keep a space before the 'USA'] -> Montana State University-Bozeman, USA
> * Sabaragamuwa University Of Srilanka [keep space between Sri and Lanka and make the L capital and add 'the'] -> The Sabaragamuwa University Of Sri Lanka
> * Above are some examples please everything for consistency.
> 
> 1. Savithru Jayasinghe is Dr as well during the time of this mentor program.
> 2. Missing people links and use their headshots from LinkedIn :
> 
> * https://www.linkedin.com/in/janidu-jayasanka-36435a145/
> * https://www.linkedin.com/in/ramithhettiarachchi/
> * https://www.linkedin.com/in/matheesha-abeysekera/
> * https://www.linkedin.com/in/najma-azmy-553928134/
> * https://www.linkedin.com/in/insaf-ismath-59b213138/ [change IM Insaf to Insaf Ismath]
> 
> 1. Remove the heading "image" -> It doesn't add much value

Sure will do the changes!

**Comment by bimsarapathiraja** [comment]
Minor suggestion,

When the cursor hovers over the profile picture or the name the cursor doesn't change itself into a hand symbol like for a hyperlink case. Checked it with both Chrome and Safari desktop versions.

**Pull request merged**
