### PR TITLE
Add SEO meta tags to the site

### LINKED ISSUE #509: Add SEO meta tags to the site
**Is your feature request related to a problem? Please describe.**
Meta tags that came with Creative Tim UI kit were not replaced and now it shows there description for our site
image

**Describe the solution you'd like**
Add SEO meta tags into the `<head></head>` 

**Describe alternatives you've considered**
N/A

**Additional context**
*We will provide the descriptions and titles and images that need to be set for the meta tags by updating this issue.*

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #509 

## Goals

- Add SEO meta tags into the <head></head> 

## Approach

- Use hero images on each page as the image.
- Use the same hero description as the description.
- Change author to Sustainable Education Foundation.  

### Preview Link

https://pr-510-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Gravewalker666** [comment]
@anjula-sack Can you please add the image meta tag and set hero images as the content?

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
@anjula-sack Can you please add the image meta tag and set hero images as the content?

**Comment by anjula-sack** [comment]
sure

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
Following pages still haven't updated
- Onelive
- ScholarX
- Team
- Join us

**Comment by anjula-sack** [comment]
Screenshot from 2020-02-16 14-23-45
onelive is updated. isn't it?

**Review by yozaam — APPROVED** [review]

**Review by Gravewalker666 — APPROVED** [review]
@anjula-sack Exquisite!
Well done mate!

**Pull request merged**
