### PR TITLE
Replace team.json with a google sheet 

### LINKED ISSUE #1001: Use a google sheet to the team page instead of JSON file
**Is your feature request related to a problem? Please describe.**
Currently, the team page is using a JSON file (assets/content/json/team.json) to import data. It's more efficient to use a google sheet to update the data than using a JSON file.

**Describe the solution you'd like**
1. Instead of using the JSON file, create a new google sheet and add the data into the sheet
2. Create a google script to export the data as a URL
3. Use the URL to import data from the sheet to the web page

### PR DESCRIPTION
**Pull request by miniskynet**
## Purpose

The purpose of this PR is to fix #1001

## Goals

To replace the assets/content/json/team.json file with a google sheet

## Approach

1) Created a google sheet with separate tabs for each respective section(advisory panel, external collaborators, etc.) , and entered the data.
[Google sheet link](https://docs.google.com/spreadsheets/d/1fcoXrjeJUSxcU6d3x2-SvNhkR76H05sTbf8h4RfWJgU/edit?usp=sharing)

2) Created a google apps script to export data from the google sheet as a URL.

3) Replaced the team.html files' URL from team.json file location to apps script deployment URL.

4) Deleted team.json file.

### Screenshots

**After making the necessary changes(team section loads perfectly) :**
image

  
### Preview Link

https://pr-1021-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by miniskynet** [comment]
@anjula-sack helped me write the script, since my knowledge in scripting is not that sharp. @Gravewalker666 @gajindubandara can you guys please take a look at this and let me know if everything is working fine?
Thank you :)

**Comment by gajindubandara** [comment]
> @anjula-sack helped me write the script, since my knowledge in scripting is not that sharp. @Gravewalker666 @gajindubandara can you guys please take a look at this and let me know if everything is working fine?
> Thank you :)

Please transfer the ownership of the Google sheet to the SEF account. Also, give me the edit access

**Review by Gimhan-minion — COMMENTED** [review]
Good Job @miniskynet This looks great!. There are some minor changes to be done. I ran a difference check between the previous JSON file and the new JSON you generated using google scripts. There's a slight difference in structure.

Screenshot from 2021-07-15 13-32-22

Before you change the structure of the JSON, @janethavi WDTY about the new structure? Do we need a separate wrapper called "social"? 

Once again Awesome Work!!! 
P.S :- Please squash the multiple commits to a single 🤗

**Comment by miniskynet** [comment]
image
@gajindubandara the ownership was transferred :)

**Comment by miniskynet** [comment]
@Gimhan-minion Hello, thank you for taking the time to run a difference check. Apart from squashing the commits, what else do I have to do?

**Comment by gajindubandara** [comment]
> image
> @gajindubandara the ownership was transferred :)

Ok  Thanks!

**Comment by Gimhan-minion** [comment]
> @Gimhan-minion Hello, thank you for taking the time to run a difference check. Apart from squashing the commits, what else do I have to do?

The rest looks great! Ping me when you've squashed the commits. 💯

**Comment by miniskynet** [comment]
@Gimhan-minion I force pushed a new commit with the same changes, instead of squashing them. Please take a look. Thank you :)

**Comment by miniskynet** [comment]
@janethavi can you please take a look at this?

**Review by janethavi — APPROVED** [review]
Great Work @miniskynet. Because we are maintaining the data on a sheet now instead of a JSON format, I also think `social` is not required. Very thoughtful idea. In the future, if we get another social media account link from each person we can add it as a new column to the sheet.

**Comment by miniskynet** [comment]
yes @janethavi as per the discussion we had on the dev call, I felt that a social tab would be redundant due to the fact that we are using a google sheet. In the future if we are adding further social media accounts we always have the option to add further columns :) Glad you share the same insight. 
Is it okay if I delete this branch?

**Pull request merged**
