### PR TITLE
Implement University filters with dynamic rendering

### LINKED ISSUE #1466: Implement filter by UNIVERSITY for the mentees in ScholarX Archive page
**Is your feature request related to a problem? Please describe.**
The Mentees of the ScholarX Archive page cannot be filtered by their University.

**Describe the solution you'd like**
Implement filter by University ONLY for the mentees on the ScholarX Archive page.

**Describe alternatives you've considered**
None

**Additional context**
Screenshot 2022-12-09 at 10 31 18

Previous PR for Archive section: Implementing COHORT filters #1453
Ongoing: Implement INDUSTRY filters  #1465

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by janithlahirukariyawasam**
## Purpose

The purpose of this PR is to fix #1466 

## Goals

The goal is to render the university dropdown with filter functionality.

  
### Preview Link

https://pr-1520-sef-site.surge.sh/
https://pr-1520-sef-site.surge.sh/scholarx/archive/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by janithlahirukariyawasam** [comment]
1. There will be no mentee results from year 2022 to 2026 because of the empty fields. (We only added the mentors details)
2. When we use Year by filters, current selection of university filters will be cleared. Is it ok or need to be improved?
3. Opinion about university filter dropdown design? is it ok? 
@anjula-sack can you review this?

**Comment by anjula-sack** [comment]
> 1. There will be no mentee results from year 2022 to 2026 because of the empty fields. (We only added the mentors details)
> 2. When we use Year by filters, current selection of university filters will be cleared. Is it ok or need to be improved?
> 3. Opinion about university filter dropdown design? is it ok?
>    @anjula-sack can you review this?

The university filter needs to be a checkbox. For ex: If I want to select mentees from UoP and UoK, the dropdown will not do it. @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
@anjula-sack Can you check now? There are two University of Moratuwa checkboxes due to different way of naming in sheet side

**Comment by janithlahirukariyawasam** [comment]
> @anjula-sack Can you check now? There are two University of Moratuwa checkboxes due to different way of naming in sheet side

Fixed! from the sheet side. There was an extra **'.'** after the university name  ( eg: University of Moratuwa.)

**Comment by anjula-sack** [comment]
Looks great! @janithlahirukariyawasam. What do you think @Madhawa97? We can improve the design a bit later.

**Comment by janithlahirukariyawasam** [comment]
@anjula-sack 
1. Increased uni filter width and height
2. left align the text
3. Converted to lowercase

**Review by anjula-sack — CHANGES_REQUESTED** [review]
The checkbox tick is not showing @janithlahirukariyawasam 
image

**Comment by Madhawa97** [comment]
> Looks great! @janithlahirukariyawasam. What do you think @Madhawa97? We can improve the design a bit later.

I'm sorry @anjula-sack. Somehow I've missed this notification. The filter looks great with the recent changes. Great job @janithlahirukariyawasam 

Will it be possible to sort the list of universities? maybe alphabetically. @janithlahirukariyawasam

**Comment by janithlahirukariyawasam** [comment]
> > Looks great! @janithlahirukariyawasam. What do you think @Madhawa97? We can improve the design a bit later.
> 
> I'm sorry @anjula-sack. Somehow I've missed this notification. The filter looks great with the recent changes. Great job @janithlahirukariyawasam
> 
> Will it be possible to sort the list of universities? maybe alphabetically. @janithlahirukariyawasam

Thank you Madhawa for the suggestion. Can you check now? And also can give me some suggestion about #1525 this profile model pr? is it ok?

**Review by anjula-sack — APPROVED** [review]
Good job! @janithlahirukariyawasam

**Pull request merged**
