### PR TITLE
CSS Of join us corrected

### LINKED ISSUE #770: CSS issue in join-us page FAQ section
**Describe the bug**
In the Join-Us page FAQ section, CSS is not the same as the rest of the FAQ sections which are in One-Live page, ScholarX etc. We need to follow the same CSS settings which are used in the rest of the FAQ sections to make the website look more consistent. Even the `+` button to expand the card is also in a different colour.

**To Reproduce**
1. Join-us page
2. Scroll down to the FAQ section 
3. Go to the One live page
4. See the difference.

**Expected behavior**
Join-us Page should also use the same CSS setting for FAQ which are used by the rest of the pages

### PR DESCRIPTION
**Pull request by shivangigoel1302**
## Purpose

The purpose of this PR is to fix  #770

### Preview Link

https://pr-778-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by janethavi** [comment]
@shivangigoel1302 Will you be able to update your pull request template content with the `Issue number` and the `PR number` eg:-

```
Purpose
The purpose of this PR is to fix #<issue_number>

Preview Link
https://pr-<PR_NUMBER>-sef-site.surge.sh/
 ```

**Comment by shivangigoel1302** [comment]
> @shivangigoel1302 Will you be able to update your pull request template content with the `Issue number` and the `PR number` eg:-
> 
> ```
> Purpose
> The purpose of this PR is to fix #<issue_number>
> 
> Preview Link
> https://pr-<PR_NUMBER>-sef-site.surge.sh/
> ```

Yes I have done the changes now

**Review by janethavi — CHANGES_REQUESTED** [review]
Great Work @shivangigoel1302!
A small addition needs to be done. If you check other FAQ containing pages such as OneLive page, once the `+` button is clicked in one FAQ, a white colour box will appear. Also the `+` is clickable. But in the join Us page the function is not the same.

This function is controlled by a js file `/assets/js/functions.js"`. Function name is `loadFaqComponent()`. 

**Requested additions**
1) In the join-us HTML file you need to import the js file in line number 264
2) You need to add the function name(`loadFaqComponent()`) into the functions component in line number 267

**Comment by shivangigoel1302** [comment]
I have done the changes. Do check

**Comment by janethavi** [comment]
Nice Work! 🚀 @shivangigoel1302 
Thank you :)

**Review by janethavi — APPROVED** [review]

**Review by Gimhan-minion — APPROVED** [review]
Thank you @shivangigoel1302 :100:

**Review by Piumal1999 — APPROVED** [review]
Good job @shivangigoel1302

**Review by jayasanka-sack — APPROVED** [review]
Thanks, @shivangigoel1302 for getting this done! 👌

Also thank you @janethavi @Piumal1999 and @Gimhan-minion for reviewing! ❤️

**Pull request merged**
