### PR TITLE
Remove unwanted button in OneLive page (#870)

### LINKED ISSUE #870: Remove unwanted button in OneLive page
**Describe the bug**
In the [OneLive Page](https://sefglobal.org/onelive/) `Take a look at our past One Lives` section there is a button called `SEE MORE`. But on other pages such as the [Team Page](https://sefglobal.org/team.html) `Alumni` section, there is just a hyperlink and no button. 

**To Reproduce**
1. Go to `Onelive Page`  and to the `Teams page`
2. See the difference.

**Expected behavior**
The `SEE MORE` button of the Onelive page should be removed and there should only be a hyperlink just as the Teams page.

### PR DESCRIPTION
**Pull request by josemsanchez**
## Purpose

The purpose of this PR is to fix #872

## Goals

Remove unwanted button in OneLive page, replace the button with hyperlink
 
## Approach

Use `btn-link btn-outline-white btn-info` css class

### Preview Link

https://pr-872-sef-site.surge.sh/

##  Checklist
- [X] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [X] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
Chrome, Windows 10

### CODE REVIEW

**Review by janethavi — CHANGES_REQUESTED** [review]
Thank you very much for your quick work.

A small change in the PR template. The PR number is `872`. Therefore will you be able to change the preview link from `https://pr-870-sef-site.surge.sh/` to `https://pr-872-sef-site.surge.sh/`

**Comment by josemsanchez** [comment]
I am happy to help. I changed the preview link.

**Review by janethavi — APPROVED** [review]
Great work! Thank you for your contribution. 💯

**Review by Gimhan-minion — APPROVED** [review]
Thank you @josemsanchez 🤗

**Pull request merged**
