### PR TITLE
Introduce checkboxes to mentors section of ScholarX-21

### LINKED ISSUE #1112: Introduce checkboxes to mentors section of ScholarX-21
**Describe the bug**
On the `mentors section` of the [Scholarx-21](https://sefglobal.org/scholarx/2021/) page, currently, there are buttons to filter the mentors. Instead of buttons, it will be a good UX feature if we introduce checkboxes. 

**To Reproduce**
1. Go to [Scholarx-21](https://sefglobal.org/scholarx/2021/) page
2. Scroll down to `Mentors section`
3. See the buttons

**Expected behavior**
The mentor filtering options should be on checkboxes while the `Show All` will be kept as a button. Once the `Show All` button is clicked, all the options should be checked and the entire list should be displayed. Additionally, these checkboxes should be center-aligned instead of left align.

### PR DESCRIPTION
**Pull request by lilRaptor99**
## Purpose

The purpose of this PR is to fix #1112 

## Goals

-  Introduce checkboxes to filter the mentor list on the ScholarX-21 page.
## Approach

- Added a set to store the selected categories.
- Created a new function to toggle the checkboxes and to add and remove the selected categories to the set.
- Added a style class to format the button with the checkbox properly

### Screenshots

  
image
image

### Preview Link

https://pr-1121-sef-site.surge.sh/scholarx/2021/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
- Node Live Server
- Google Chrome
- Windows 10 x64

### CODE REVIEW

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
Good job @lilRaptor99 

I have few suggestions.
Can we show some kind of message when the user haven't selected any of the categories? Otherwise, it will be empty.

Also, let's tick all the categories after loading the mentors section because it shows mentors from every category initially.

**Comment by lilRaptor99** [comment]
> I have few suggestions. Can we show some kind of message when the user haven't selected any of the categories? Otherwise, it will be empty.
> 
> Also, let's tick all the categories after loading the mentors section because it shows mentors from every category initially.

Nice, I'll work on this.

**Comment by lilRaptor99** [comment]
image

image
Done

**Review by Piumal1999 — APPROVED** [review]
Wow!!🤩 This is really impressive. Well done @lilRaptor99

**Review by gajindubandara — APPROVED** [review]

**Review by akeel230 — APPROVED** [review]
Great work @lilRaptor99

**Pull request merged**
