### PR TITLE
Add new fields to the mentors in scholarx.

### LINKED ISSUE #516: Add new fields to the mentors in scholarx.
**Is your feature request related to a problem? Please describe.**
Required new fields for the mentors in scholarx page.

**Describe the solution you'd like**
Go to the scholarx.json file
Add these fields.
Screenshot from 2020-02-24 11-41-45

**Additional context**

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #516 

## Goals

- Add new fields to the mentors in scholarx

## Approach

- Go to the scholarx.json file
- Add these fields.
Screenshot from 2020-02-24 11-41-45

  
### Preview Link

https://pr-517-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Piumal1999 — DISMISSED** [review]

**Comment by Gravewalker666** [comment]
@anjula-sack Can you please resolve the conflict in the JSON file?

**Comment by anjula-sack** [comment]
> @anjula-sack Can you please resolve the conflict in the JSON file?

I fixed it.

**Review by Gravewalker666 — APPROVED** [review]
Greate Job @anjula-sack 
Thanks!!

**Review by jayasanka-sack — COMMENTED** [review]
This should be reorganized as follows,

social links have to go under a new key and it should be an array.
```
"socialLinks" : [
   {
    "platform" : "Linkedin",
    "icon" : "fa-linkedin",
     "url" : "..."
   },
    {
    "platform" : "Facebook",
    "icon" : "fa-linkedin",
     "url" : "..."
   },
]
```

Same with the project. The key should be "projects" and it should be an array.

The keys should not contain white spaces and must use **Simple Camel Case** format.

@anjula-sack  Please create a new issue for this

**Comment by anjula-sack** [comment]
> This should be reorganized as follows,
> 
> social links have to go under a new key and it should be an array.
> 
> ```
> "socialLinks" : [
>    {
>     "platform" : "Linkedin",
>     "icon" : "fa-linkedin",
>      "url" : "..."
>    },
>     {
>     "platform" : "Facebook",
>     "icon" : "fa-linkedin",
>      "url" : "..."
>    },
> ]
> ```
> 
> Same with the project. The key should be "projects" and it should be an array.
> 
> The keys should not contain white spaces and must use **Simple Camel Case** format.
> 
> @anjula-sack Please create a new issue for this

I made an issue for this @jayasanka-sack

**Pull request merged**
