### PR TITLE
Fix the Scholarx page alignments

### LINKED ISSUE #1272: Fix the Scholarx page alignments
**Describe the bug**
Currently, the width of the scholarx page is increased

**To Reproduce**
1. Go to 'Scholarx Page'

**Expected behavior**
Reduce the width of the scholarx page

**Screenshots**
See the horizontal scroll bar

image

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #1272 

## Goals

Fixing the Scholarx page alignments

## Approach

Fixed the Scholarx page alignments

### Screenshots

Check now no horizontal scroll bar

image

  
### Preview Link

https://pr-1278-sef-site.surge.sh/scholarx/2022

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Piumal1999 — COMMENTED** [review]
Seems like this is already fixed with #1277

**Comment by YoshithaRathnayake** [comment]
> Seems like this is already fixed with #1277

Is that so? wait while anjula ayya he assigned me for my issue

**Comment by YoshithaRathnayake** [comment]
@anjula-sack how about this can you merge this?

**Review by anjula-sack — APPROVED** [review]
Thank you! @YoshithaRathnayake

**Pull request merged**
