### PR TITLE
Change blog link in footer and navbar

### LINKED ISSUE #844: Update the blog link in the SEF Site
**Describe the bug**
Update the blog link in the entire website to the new link `https://sefglobal.medium.com/`
Please find the blog page access places in the following places
1) Navigation Bar
2) Footer

**Expected behavior**
The blog hyperlink should be redirected to the medium SEF Channel.

### PR DESCRIPTION
**Pull request by rocklikereeju00**
## Purpose
Change blog link (https://sefglobal.medium.com) in footer & navber .
The purpose of this PR is to fix #844 

### Preview Link

https://pr-852-sef-site.surge.sh/

### CODE REVIEW

**Review by Gimhan-minion — COMMENTED** [review]
@rocklikereeju00 Can you please add a clear description to your PR too. So that it'll be easier for other contributors to understand the changes done. 

Other than that PR code seems okay to me. Thank you for contributing. We'll merge this as soon as the description is added. 😃

**Comment by rocklikereeju00** [comment]
@Gimhan-minion , I changed my description .

**Review by janethavi — APPROVED** [review]
Good Work @rocklikereeju00! Hope you learnt something new :100:

**Comment by rocklikereeju00** [comment]
Thank you all for teach me new thinks !😘😘

**Pull request merged**
