### PR TITLE
Remove horizontal scrolling in ScholarX

### LINKED ISSUE #755: ScholarX page has horizontal scrolling
**Describe the bug**
The ScholarX page has horizontal scrolling.

**To Reproduce**
1. Go to 'https://sefglobal.org/scholarx/2020/'
2. See error

**Expected behavior**
Removing horizontal scrolling

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.04
 - Browser [e.g. chrome, safari] Google Chrome

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by janethavi**
## Purpose
Remove horizontal scrolling bar in ScholarX page
The purpose of this PR is to fix #755 

## Goals
The horizontal scrolling bar won't appear in the ScholarX page.

## Approach
Adding a body CSS for horizontal scrolling disable. 

### Preview Link
https://pr-768-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Ubuntu 18.04, Google chrome

### CODE REVIEW

**Comment by Piumal1999** [comment]
@janethavi TGood Job!!
Btw, I think we have a better solution for this bug. There's a row outside the container of 'Past ScholarX' section in scholarx/2020/index.html (Line 539). I think moving the row into the container may fix this bug. Could you please try it also

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
Good Job!! @janethavi !!
Btw, I think we have a better solution for this bug. There's a row outside the container of 'Past ScholarX' section in scholarx/2020/index.html (Line 539). I think moving the row into the container may fix this bug. Could you please try it also

**Review by Piumal1999 — APPROVED** [review]
Well done @janethavi Thank you!!

**Review by Gimhan-minion — APPROVED** [review]
Looks good to me! Thank you @janethavi :100:

**Pull request merged**
