### PR TITLE
Add project cards to engineering team page

### LINKED ISSUE #1361: Add project cards to engineering team page
**Describe the solution you'd like**
- Add project cards for projects in engineering team

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by RandilaP**
## Purpose

The purpose of this PR is to fix #1361 

### Screenshots
image

  
### Preview Link

https://pr-1359-sef-site.surge.sh/

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by RandilaP** [comment]
@anjula-sack @Piumal1999 @jayasanka-sack @kumuditha-udayanga Can u review this

**Comment by YoshithaRathnayake** [comment]
> ## Purpose
> The purpose of this PR is to Add project cards to engineering team page
> 
> ### Screenshots
> image

I think it is better to create an issue, after you assigned to it then do this @RandilaP

**Comment by RandilaP** [comment]
@YoshithaRathnayake OK. Thanks

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake OK. Thanks

You welcome @RandilaP

**Comment by kumuditha-udayanga** [comment]
@RandilaP Thank you for getting this done, I think it would look nice if the project logo is centered and the card has a padding as shown in the image below. WDYT? @anjula-sack @Piumal1999 
Screenshot 2022-10-24 at 8 47 57 PM

**Comment by YoshithaRathnayake** [comment]
> @RandilaP Thank you for getting this done, I think it would look nice if the project logo is centered and the card has a padding as shown in the image below. WDYT? @anjula-sack @Piumal1999 Screenshot 2022-10-24 at 8 47 57 PM

Yeah that's good for me also @kumuditha-udayanga

**Comment by jayasanka-sack** [comment]
> @RandilaP Thank you for getting this done, I think it would look nice if the project logo is centered and the card has a padding as shown in the image below. 

+1 for the suggestion ❤️

**Comment by RandilaP** [comment]
@kumuditha-udayanga @jayasanka-sack OK I'll look in to that.

**Comment by jayasanka-sack** [comment]
Nice suggestion, @RandilaP ! 

We can improve white spacings too.
1. `x` should be equal to `y`
2. `a` should be equal to `y`
3. `ණ` should be equal to `ඹ`

IMG_F544206F0965-1


This video might help you to get an idea: https://youtu.be/a5KYlHNKQB8

I created an interesting playlist for you! I hope you will love it 🤗:  
https://www.youtube.com/playlist?list=PLnZBpmEgobTnK8m8Mf1GPIw51m2IM1ERo

**Comment by RandilaP** [comment]
@jayasanka-sack Thank you.. I'lll watch them.

**Comment by RandilaP** [comment]
@anjula-sack @jayasanka-sack @Piumal1999 @kumuditha-udayanga Can you review it

**Review by anjula-sack — APPROVED** [review]
Thank you! @RandilaP BTW why are not showing the logos in the mobile view?

**Comment by RandilaP** [comment]
@anjula-sack I'll check that.

**Pull request merged**
