### PR TITLE
Add a section to the ScholarX page to access the success stories page

### LINKED ISSUE #1250: Add a section to the ScholarX page to access the success stories page
**Is your feature request related to a problem? Please describe.**
Currently users can't navigate to the ScholarX Success Stories page. 

**Describe the solution you'd like**
Add a section to the ScholarX page to access the success stories page.

**Describe alternatives you've considered**
None

**Additional context**
ScholarX Success Stories page was introduced with #1226

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by Madhawa97**
## Purpose

The purpose of this PR is to fix #1250 

## Goals
Currently users can't navigate to the ScholarX Success Stories page. Therefore we need to add a section to the ScholarX page to access the success stories page.

## Approach

Add a section to the ScholarX 2022 page to access the success stories page.

### Screenshots
Screenshot 2022-10-07 at 05 04 57

### Preview Link

https://pr-1259-sef-site.surge.sh/scholarx/2022/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
macOS 12.6, Chrome Version 105.0.5195.125 (Official Build) (arm64)

## Learning
https://getbootstrap.com/docs/4.0/utilities/spacing/

### CODE REVIEW

**Comment by Madhawa97** [comment]
Initially I tried without an image but since the "SX Archive Button" looks the same It didn't look good. 

Therefore I used an illustration from Freepik. I can remove it if it doesn't suite. 
Also I'd suggest to add a similar image for the Archive section as well.

@anjula-sack @Piumal1999

**Review by anjula-sack — CHANGES_REQUESTED** [review]
I think having this section after the timeline would be nice. WDYT? @Madhawa97 @Piumal1999

**Comment by Madhawa97** [comment]
@anjula-sack Yes. I also agree with that. Bottom of page would be a good place for the Archive section. 
Let me know your decision and then I'll proceed that way.

**Comment by Piumal1999** [comment]
> I think having this section after the timeline would be nice. WDYT? @Madhawa97 @Piumal1999

What if we combine the `featured stories` section and `success stories` section?

**Comment by Madhawa97** [comment]
I feel like the `featured stories` section has articles describing a certain topic, while the `success-stories` are more about the individuals and their stories. How about renaming the `Featured Stories` section to `Featured Articles` to make it more clear for the readers.
Just a suggestion though. it's your call.

**Comment by anjula-sack** [comment]
> I feel like the `featured stories` section has articles describing a certain topic, while the `success-stories` are more about the individuals and their stories. How about renaming the `Featured Stories` section to `Featured Articles` to make it more clear for the readers. Just a suggestion though. it's your call.

I agree with you! Please go ahead.

**Comment by Madhawa97** [comment]
Awesome! I added the `success-stories` section below the `featured-articles` section. Let me know what do you guys think. @anjula-sack @Piumal1999

**Comment by anjula-sack** [comment]
> Awesome! I added the `success-stories` section below the `featured-articles` section. Let me know what do you guys think. @anjula-sack @Piumal1999

What about adding the `featured-articles` section below the `success-stories` section? @Piumal1999 @jayasanka-sack

**Comment by Madhawa97** [comment]
> > Awesome! I added the `success-stories` section below the `featured-articles` section. Let me know what do you guys think. @anjula-sack @Piumal1999
> 
> What about adding the `featured-articles` section below the `success-stories` section? @Piumal1999 @jayasanka-sack

Also sounds great. Made a commit so you guys can see if it's suited that way

**Comment by Madhawa97** [comment]
@anjula-sack  I changed the text based on the feedback from the standup call

**Comment by Madhawa97** [comment]
There is an alignment issue in the entire page, due to the `archive-section` not having a `container` class. May be we I can fix it on a different ticket?

**Comment by anjula-sack** [comment]
> There is an alignment issue in the entire page, due to the `archive-section` not having a `container` class. May be we I can fix it on a different ticket?

yeah it's better

**Review by anjula-sack — APPROVED** [review]
Good job! @Madhawa97

**Pull request merged**
