### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ManojLL**
## Purpose
animate the buttons in index page
## Goals
this will make buttons body color and make them animate.
## Approach
change button  styles 
### Screenshots
Screenshot from 2019-12-26 21-28-22

  
### Preview Link
https://manojmaxma.github.io/update_index/. 

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
N/A

## Test environment
Ubuntu 18.04
Google chrome
## Learning
N/A

### CODE REVIEW

**Comment by manojmaxma** [comment]
change button styles

**Comment by Piumal1999** [comment]
@manojmaxma you have to add the description 😁

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
It seems all good with the code but we need a preview link to see the changes. Follow these steps and comment the preview link on PR.
- Go to your forked sef-site repository
- Go to settings 
- Scroll down to the git hub pages 
- Set the source to master branch
- Copy the preview link!
Enjoy! Cheers!

**Comment by jayasanka-sack** [comment]
@Gravewalker666 The button looks different from the design. Isn't it?

**Comment by Gravewalker666** [comment]
@jayasanka-sack Yeah, It kind of is. Let's wait for the preview link to get a better view!

**Pull request closed without merging**
