### PR TITLE
Reduce the height

### LINKED ISSUE #1478: Reduce the image size of OneLive page
**Is your feature request related to a problem? Please describe.**
Currently, the main image on OneLive page is very large.

**Describe the solution you'd like**
Make it little bit smaller.

**Describe alternatives you've considered**
None

**Additional context**
Screenshot 2022-12-18 at 11 06 37

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by dilankavishka**
## Purpose

The purpose of this PR is to fix #1478 

## Goals

Reduce the height of OneLive section.

## Approach

Reduced the height of OneLive section.

### Screenshots

  
Screenshot 2022-12-22 at 15 29 22

### Preview Link

https://pr-1482-sef-site.surge.sh/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by dilankavishka** [comment]
Anything need to improve? @anjula-sack

**Review by anjula-sack — CHANGES_REQUESTED** [review]
image
The image should be inside the container

**Review by YoshithaRathnayake — COMMENTED** [review]
@dilankavishka any update on this?

**Comment by anjula-sack** [comment]
@YoshithaRathnayake can you help @dilankavishka with this?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake can you help @dilankavishka with this?

Sure @anjula-sack

**Comment by YoshithaRathnayake** [comment]
@dilankavishka can you complete these requested changes?

**Comment by YoshithaRathnayake** [comment]
@dilankavishka any update on this?

**Comment by anjula-sack** [comment]
Closing as stale.

**Pull request closed without merging**
