### PR TITLE
Add Box shadows to testimonial section

### PR DESCRIPTION
**Pull request by wilsonfurtado2000**
Add Box shadows to testimonial section
issue #1136 

## Goals
This feature will improve the UI

## Approach
using CSS

### CODE REVIEW

**Comment by wilsonfurtado2000** [comment]
Please review the changes

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
Good job @wilsonfurtado2000!
But there are some unwanted formatting changes in your commit. Could you please remove those formatting changes and update the Pull Request? So it will be easy for us to review and also it's necessary for us to keep a clean commit history. 

Also, let's use something like "Add Box shadows to testimonial section" as the pull request name. You can update it by clicking the edit button on the top.

**Comment by wilsonfurtado2000** [comment]
> Good job @wilsonfurtado2000! But there are some unwanted formatting changes in your commit. Could you please remove those formatting changes and update the Pull Request? So it will be easy for us to review and also it's necessary for us to keep a clean commit history.
> 
> Also, let's use something like "Add Box shadows to testimonial section" as the pull request name. You can update it by clicking the edit button on the top.

Bro i used the standard formatting tool is vscode i guess we cant revert it

**Comment by Piumal1999** [comment]
Closing due to no activity

**Pull request closed without merging**
