### PR TITLE
Fix testimonial font size in responsive view

### LINKED ISSUE #1128: Testimonials are not responsive in mobile view
**Describe the bug**
Font size in mobile view.

**To Reproduce**
1. Go to 'https://sefglobal.org/'
2. Scroll down to 'last page'
4. Glitch in font size

**Expected behavior**
Reduce the font size such that everything should be see clear.

**Screenshots**
image

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max 
 - OS:  14.6
 - Browser: firefox
 - Version: latest

### PR DESCRIPTION
**Pull request by MRIDUL-MB**
## Purpose
bug in font size on mobile and tab responsive
The purpose of this PR is to fix #1128

## Goals
 Reduce font size according to the screen 

### Screenshots
image
image

### Preview Link

https://pr-1129-sef-site.surge.sh/

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
OS: windows
Browser: Firefox
Version: Latest

### CODE REVIEW

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
Good job @MRIDUL-MB. But there are 569 line changes due to the formatting changes in the commit. Could you please remove the unwanted changes and update the pull request. Let us know if you have any trouble.

**Comment by MRIDUL-MB** [comment]
That's because I am using VS Code editor in which there is a Prettier-code formatter extension that is used to format the document. So when I save the document it's automatically formatted.
I believe there would be no issue with the format of the document.

**Comment by Piumal1999** [comment]
@MRIDUL-MB Yeah. But we need to prevent unwanted line changes to maintain a clean commit history. Could you please fix it, so we can merge the Pull request.

**Comment by Piumal1999** [comment]
Closing due to no activity

**Pull request closed without merging**
