### PR TITLE
Align cards vertically in small screen size in our projects section

### LINKED ISSUE #1621: Align the Our projects section within small screen size.
**Describe the bug**
Currently, our projects section is not aligned well in small screen size. 

**To Reproduce**
1. Go to [https://sefglobal.org/](https://sefglobal.org/)
2. Change the screen size so that the screen size becomes small (768px>screen size>576px)
3. Scroll down to 'Our projects' section

**Expected behavior**
Align the project section using bootstrap.

**Screenshots**
F-1

F-2

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by Isuru4043**
## Purpose
The purpose of this PR is to fix  #1621 

## Goals
Vertically aligning cards where words were confused in small screen size.

## Approach
Change the min-width from 576px to 768px in media query.

### Screenshots
**before**
F-2
F-1

**after**  
f-4
f-3

### Preview Link
[https://pr-1622-sef-site.surge.sh/](https://pr-1622-sef-site.surge.sh/)

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
I think we can't edit the argon.css file. @anjula-sack Can we?

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Can you update the preview link? @Isuru4043 
You should include the pr number except this {PR_NUMBER}
Ex: https://pr-0000-sef-site.surge.sh/

**Comment by Isuru4043** [comment]
@YoshithaRathnayake  sure, I'll update the preview link.

**Review by YoshithaRathnayake — COMMENTED** [review]
The changes are good! @Isuru4043 Thank you but I can't merge this bcs I don't know whether we can't change the argon.css file. I will ask from anjula ayya. @anjula-sack ?

**Comment by anjula-sack** [comment]
> The changes are good! @Isuru4043 Thank you but I can't merge this bcs I don't know whether we can't change the argon.css file. I will ask from anjula ayya. @anjula-sack ?

You are correct @YoshithaRathnayake. We shouldn't be updating argon.css file. @Isuru4043 Can you override it on the relevant CSS file?

**Comment by Isuru4043** [comment]
@anjula-sack Can we update the global-custom.css file

**Comment by Isuru4043** [comment]
Can we change the [global-custom.css](https://github.com/sef-global/sef-site/tree/master/assets/css/global-custom.css) file.  @anjula-sack

**Comment by YoshithaRathnayake** [comment]
> Can we change the [global-custom.css](https://github.com/sef-global/sef-site/tree/master/assets/css/global-custom.css) file. @anjula-sack

Yeah you can @Isuru4043

**Review by YoshithaRathnayake — COMMENTED** [review]
Any updates? @Isuru4043

**Pull request closed without merging**
