### PR TITLE
Initiate the ScholarX 2021 page

### LINKED ISSUE #815: Update to new scholarX-21
**Is your feature request related to a problem? Please describe.**
1) ScholarX-20 page should be updated to ScholarX-21.
2) ScholarX-20 should be added to the achieve list. 
3) All the links need to be redirected from ScholarX-20 to ScholarX-21.

### PR DESCRIPTION
**Pull request by janethavi**
## Purpose
Remove the old content of ScholarX-20 to archive and update the page to ScholarX-21
The purpose of this PR is to fix #815 

## Goals
1) Add new ScholarX-21 page
2) Added the new timeline to ScholarX-21
3) Move ScholarX-20 to archive
4) Update the Archive page by adding a new card
5) Update the links from navigation and from home to redirect to the new scholarX-21 page.

### Screenshots
Screenshot from 2020-11-20 20-20-51
Screenshot from 2020-11-20 20-21-03

  
### Preview Link
https://pr-816-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Chrome, Ubuntu 20.04

### CODE REVIEW

**Review by NaviRocker — COMMENTED** [review]
Preview Link is broken

**Comment by janethavi** [comment]
> Preview Link is broken

Seems like there is an issue with the Travis CI. The process of building the project is queued.

**Review by jayasanka-sack — APPROVED** [review]
Thank you very much for getting this done @janethavi! 

Also thanks, @NaviRocker for reviewing the PR!

**Comment by NaviRocker** [comment]
Good Job @janethavi

**Pull request merged**
