### PR TITLE
Add fixed position to Linkedin icon

### LINKED ISSUE #800: LinkedIn icon of profile pics in teams page changes position with the window's width
**Describe the bug**
When changing the browser window's width LinkedIn item changes vertical position.

**To Reproduce**
1. Go to https://sefglobal.org/team.html.
2. Scroll down to a profile.
3. Change the width of the window using dev tools while hovering the profile.

**Expected behavior**
The LinkedIn icon should be in a fixed position on the profile pic.

**Screenshots**
<p float="left">
  
   
</p>

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by nisan-abeywickrama**
## Purpose

The purpose of this PR is to fix #800 

## Goals

Solving the issue of LinkedIn icon position change with window width

## Approach

Setting the position to relative and updating the top property.

https://pr-806-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gravewalker666 — APPROVED** [review]
Amazing work @nisan-abeywickrama

**Review by YohanAvishke — APPROVED** [review]
Great job @nisan-abeywickrama 🚀

**Review by Piumal1999 — APPROVED** [review]
Well done @nisan-abeywickrama 
Thank you

**Review by janethavi — APPROVED** [review]
Great Work @nisan-abeywickrama! 💯

**Pull request merged**
