### PR TITLE
Change the order of the project cards

### LINKED ISSUE #1123: Change the order of the cards
**Describe the bug**
On the home page under the `Our Projects` section the card order needs to be changed. The same order needs to be applied to the navigation bar, projects menu.

**To Reproduce**
1. Go to [https://sefglobal.org/](https://sefglobal.org/)
2. Scroll down to `Our Projects` section
3. See the current order
4. See the navigation bar projects list as well

**Expected behavior**
The order should be as follows.

`Home page cards order`
1st Line :- ScholarX -> IRC -> OneLive
2nd Line :-  Academix -> UpSpeak -> Student Ambassador

`Projects menu order` (Already fixed with #1124)
1. ScholarX 
2. IRC
3. OneLive
4. Academix 
5. UpSpeak
6. Student Ambassador

### PR DESCRIPTION
**Pull request by ghost**
## Purpose

The purpose of this PR is to fix #1123

## Goals

Changing the order of the cards in "Our Projects" section.

## Approach

I cut the codes of the cards from incorrect place and paste it in the correct place 

### Screenshots

  SEF Our Projects 1 st Row
SEF Our Projects 2 nd Row

### Preview Link

https://pr-1154-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Piumal1999** [comment]
Good job @YoshithaRathnayake2008 

Could you please update the pull request description by adding the issue number, goals, approach, and preview link?

(It automatically generates a preview link with this format: https://pr-{pull_request_number}-sef-site.surge.sh/ 
So in this PR, the preview link is https://pr-1154-sef-site.surge.sh/)

**Comment by ghost** [comment]
Piumal Brother, I made the changes again.

**Review by Piumal1999 — APPROVED** [review]
Awesome! @YoshithaRathnayake2008 
Thank you

**Comment by ghost** [comment]
Your Welcome! 😀

**Pull request merged**
