### PR TITLE
Reduce image size of student ambassador page

### LINKED ISSUE #1479: Reduce the image size of Student Ambassador page
**Is your feature request related to a problem? Please describe.**
Currently, the main image on Student Ambassador page is little bit large.

**Describe the solution you'd like**
Make it little bit smaller.

**Describe alternatives you've considered**
None

**Additional context**
Screenshot 2022-12-18 at 11 16 08

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by dilankavishka**
## Purpose

The purpose of this PR is to fix #1479

## Goals

Reduce the main image size of Student Ambassador page.

## Approach

Reduced the main image size of Student Ambassador page.

### Screenshots

  
Screenshot 2022-12-20 at 10 18 34

### Preview Link

https://pr-1481-sef-site.surge.sh/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by dilankavishka** [comment]
No problem, right? @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> No problem, right? @YoshithaRathnayake

Yes looks good for me @dilankavishka 
@anjula-sack any changes requested? Can we merge this?

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Good job! @dilankavishka. can you add the image inside the container? See the margin in other divs. 

image

**Comment by dilankavishka** [comment]
yeah sure. @anjula-sack

**Review by YoshithaRathnayake — COMMENTED** [review]
@dilankavishka any update on this?

**Comment by anjula-sack** [comment]
@YoshithaRathnayake can you help @dilankavishka with this?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake can you help @dilankavishka with this?

Sure @anjula-sack

**Comment by YoshithaRathnayake** [comment]
@dilankavishka can you complete these requested changes?

**Comment by YoshithaRathnayake** [comment]
@dilankavishka any update on this?

**Comment by anjula-sack** [comment]
Closing as stale.

**Pull request closed without merging**
