### PR TITLE
Added missed links for buttons

### PR DESCRIPTION
**Pull request by BhathiyaTK**
## Purpose

Resolve issue #287 

## Goals
Adding relevant links for buttons.

## Approach
Added missing link attributes with relevant links.

### Screenshots
N/A
  
### Preview Link
N/A

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
N/A

## Test environment
Firefox Developer Edition v72.0b11, Google Chrome Dev v81.0.4000.3, Opera Browser v65.0.3467.78, Microsoft Edge v44.18362.449.0

## Learning
N/A

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
@BhathiyaTK There are 6 files changed. Including home page and footer.
Could you please commit only the change which is relevant to this PR?

**Comment by Piumal1999** [comment]
> @BhathiyaTK There are 6 files changed. Including home page and footer.
> Could you please commit only the change which is relevant to this PR?

Yes. You only have to add the links for buttons on onelive page @BhathiyaTK .

**Comment by BhathiyaTK** [comment]
@jayasanka-sack @Piumal1999 I will do.

**Review by BhathiyaTK — COMMENTED** [review]
Removed the change that done to other files except onlive page.

**Comment by Piumal1999** [comment]
Few important files were deleted on your pr. And the branch has conflicts. I think its better if you can update and sync your repo before sending the pr.
@BhathiyaTK

**Comment by BhathiyaTK** [comment]
Okay. I will fix the issue then close this PR and create a new PR.

**Pull request closed without merging**
