### PR TITLE
Update content of Our Journey So Far section

### LINKED ISSUE #1168: "Our Journey so far" section information update
**Is your feature request related to a problem? Please describe.**
The information in our journey so far section is outdated. and a HIVE thread is created by @akshika47 with the new data input.

**Describe the solution you'd like**
Get the information from the Hive thread and replace the info with the existing data for the same structure design
https://sef.discourse.group/t/change-our-journey-so-far-content-on-the-landing-page/390

**Additional context**
The design will be the same only the data is to be updated

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by Madhawa97**
## Purpose
The purpose of this PR is to fix #1168 

## Goals
The information in our journey so far section is outdated. The goal of this PR is to update the our journey so far section with the information given in the HIVE thread, which was created by @akshika47 with the new data input. 

## Approach
Get the information from the Hive thread and replace the info with the existing data for the same structure design
https://sef.discourse.group/t/change-our-journey-so-far-content-on-the-landing-page/390

### Screenshots
image

Mobile View:
image
image
image

  
### Preview Link
https://pr-1169-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
Add Our Journey So Far Section to the Homepage #1151 

## Test environment
macOS Monterey 12.2.1

### CODE REVIEW

**Comment by akeel230** [comment]
@Madhawa97 good job mate as always. @akshika47 please check now. @Piumal1999 please second review the code and approve

**Comment by Madhawa97** [comment]
Thank you @akeel230

**Review by Piumal1999 — DISMISSED** [review]
Looks good. @Madhawa97 Thank you very much for getting this done.

**Comment by Madhawa97** [comment]
Thank you @Piumal1999

**Comment by Madhawa97** [comment]
@Piumal1999 @akeel230 I updated the timeline to a vertical one.

**Comment by jayasanka-sack** [comment]
@akeel230 @Piumal1999 Can we merge this?

**Comment by Piumal1999** [comment]
Yeah, let's merge this.

**Review by Piumal1999 — APPROVED** [review]

**Comment by akeel230** [comment]
@Madhawa97 great work

**Pull request merged**
