### PR TITLE
Create "our mentors are from" section

### LINKED ISSUE #701: Create "our mentors and speakers are from" section
**Is your feature request related to a problem? Please describe.**
Need a section to display the logos of the institutes and organisations where the mentors and speakers work

**Describe the solution you'd like**
Create the relevant component

**Describe alternatives you've considered**
N/A

**Additional context**
Use the landing-page branch

### PR DESCRIPTION
**Pull request by Piumal1999**
## Purpose

The purpose of this PR is to fix #701 

## Goals

Create "our mentors are from" section

## Approach

Added the logos
Created the section

### Screenshots

Logo section
Home_Sustainable_Education_Foundation_-_2020-06-02_02 29 59
<br>
Footer
Home_Sustainable_Education_Foundation_-_2020-06-02_02 30 37

### Preview Link

https://pr-702-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs

N/A

## Test environment
 
Ubuntu 19.10
Google Chrome

## Learning

N/A

### CODE REVIEW

**Comment by akshika47** [comment]
Need more breathing space between logos vertically and horizontally. Take a look at the example we originally discussed this. 

The message at the bottom should come before the vertical line above "© 2020 Sustainable Education Foundation - SEF.". Left align the text rather than right. Keep some space from the right side as well. 
image

And the drop the *yet* part from the line. It does not look professional(It was my suggestion, sorry).

<Add some space here>*Our mentors and speakers engage in mentoring and speaking voluntarily in their leisure time
and we don't have a direct affiliation with the mentioned organisations.

**Comment by Piumal1999** [comment]
Ah ok😁. I'll update the PR. Thanks @akshika47

**Comment by akshika47** [comment]
Good job! Let's get this PR closed today.

**Comment by akshika47** [comment]
@Piumal1999 any blockers? How is the progress with this ticket?

**Comment by Piumal1999** [comment]
Still working on this. @akshika47 sorry for the delay

**Review by Gimhan-minion — APPROVED** [review]
Awesome @Piumal1999  :partying_face:

**Review by akshika47 — APPROVED** [review]

**Pull request merged**
