### PR TITLE
Add new button for redirect to scholarx platform

### LINKED ISSUE #1635: Add a button to got to scholarx on the new scholarx page
**Is your feature request related to a problem? Please describe.**
Currently, there is no direct way to navigate from the ScholarX 2023 page to the new ScholarX platform. This can cause confusion and inconvenience for users looking to access the updated platform.

**Describe the solution you'd like**
Add a button on the https://sefglobal.org/scholarx/2023/ page that directs users to the new ScholarX platform at https://scholarx.sefglobal.org/.

**Describe alternatives you've considered**

**Additional context**

Here is an image showing the current ScholarX 2023 page where the new button should be added:

image

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by kamalchakma1**
## Purpose

The purpose of this PR is to fix #1635

## Goals

-  To add new button which will redirect from https://sefglobal.org/scholarx/2023/ to https://scholarx.sefglobal.org/

## Approach

- I have added button which is redirect from https://sefglobal.org/scholarx/2023/ to https://scholarx.sefglobal.org

### Screenshots

after

### Preview Link

https://pr-1636-sef-site.surge.sh/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Hi @kamalchakma1, Can we add the button below the main paragraph
image


Also use the blue color button and change the button text to visit scholarx.

**Comment by kamalchakma1** [comment]
Hey, yes  we can do that. I will do it.

**Comment by mayura-andrew** [comment]
how about add VISIT SCHOLARX 2024? @anjula-sack

**Comment by kamalchakma1** [comment]
Hi, I have added the changes. can you check once?

buttonadded

**Comment by mayura-andrew** [comment]
can add space between new button and that container ?
image

**Comment by kamalchakma1** [comment]
hi @mayura-andrew , I have added space between button and other containers, please have a look.

spaceadded

**Review by anjula-sack — APPROVED** [review]
Thank you! @kamalchakma1

**Comment by mayura-andrew** [comment]
@kamalchakma1 Good Job! Thank you :)

**Comment by kamalchakma1** [comment]
> Thank you! @kamalchakma1 

You welcome !

**Comment by kamalchakma1** [comment]
> @kamalchakma1 Good Job! Thank you :)

Thank you! You welcome

**Pull request merged**
