### PR TITLE
Changed Dev team on the Team page to Engineering team

### LINKED ISSUE #1116: Rename the Dev team name with Engineering team in the Team pages
**Is your feature request related to a problem? Please describe.**
We have decided to rename the Dev team as the Engineering team. We need to change the name in the teams page 

**Describe the solution you'd like**

Screenshot (475)

**Describe alternatives you've considered**
To recreate go to team.html see the h1 tag which has the Dev team name, replace it with Engineering team name

### PR DESCRIPTION
**Pull request by jaebirds**
## Purpose

The purpose of this PR is to fix #1116

### Preview Link

https://pr-1119-sef-site.surge.sh/

##  Checklist
- [X] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [X] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by janethavi — COMMENTED** [review]
You have done a good job. Few little things to be corrected. In your PR template, will you be able to add the issue number after `#`? The reason to do that is when we merge your PR the issue will be automatically closed. It's better if you can fill the PR headings. At least the `approach` section by mentioning what you did. It's done as a best practice. Also, the PR link should be corrected to as [https://pr-1119-sef-site.surge.sh](https://pr-1119-sef-site.surge.sh ). You can visit that link and have a preview of what you did on your PR. The checkboxes should be checked too.

**Comment by akeel230** [comment]
hey, there @jaebirds can u please make the changes that @janethavi has requested. Then your PR can be merged.

**Comment by jaebirds** [comment]
The changes have been done, sorry about that!

**Comment by akeel230** [comment]
@jaebirds Good job

**Comment by janethavi** [comment]
Looks like @jaebirds has missed adding a small description to the approach section.

**Comment by jaebirds** [comment]
> Looks like @jaebirds has missed adding a small description to the approach section.

It's such a minor change, I'm not sure what I would even write.

**Comment by Gravewalker666** [comment]
> > Looks like @jaebirds has missed adding a small description to the approach section.
> 
> It's such a minor change, I'm not sure what I would even write.

Yeah true, after all it's just changing a text :)

**Review by Gravewalker666 — APPROVED** [review]
Thank you @jaebirds for getting this done

**Pull request merged**
