### PR TITLE
Update the ScholarX 2021 hero image 

### LINKED ISSUE #827: Update ScholarX 2021 hero image
**Is your feature request related to a problem? Please describe.**
 Add the photo from Vladimir’s session to the Scholarx 2021 page.

### PR DESCRIPTION
**Pull request by DilshanNaveen**
## Purpose
Purpose of this pr to fix #827

## Goals
Update the ScholarX 2021 hero image

## Preview Link
https://pr-828-sef-site.surge.sh/

### Screenshots

- Before

image

- After

image

  
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Google Chrome, macOS Big Sur 11.1

### CODE REVIEW

**Review by YohanAvishke — CHANGES_REQUESTED** [review]
Hi @DilshanNaveen thanks a lot for the PR. 
There seems to be others commits in the PR. You can `rebase` and drop all the commits excluding your ones. 
You can learn more about rebasing from [here](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

**Review by janethavi — APPROVED** [review]
Thank you @DilshanNaveen! Great Work 💯

**Review by jayasanka-sack — APPROVED** [review]
Thanks @DilshanNaveen !

**Review by YohanAvishke — APPROVED** [review]
Awesome job, @DilshanNaveen 😍

**Comment by DilshanNaveen** [comment]
Thanks 😀️

**Pull request merged**
