### PR TITLE
Add Contact US section to ScholarX archive

### LINKED ISSUE #1556: Add contact us section for ScholarX archive
**Is your feature request related to a problem? Please describe.**
There needs to be a mechanism for mentors and mentees to inform us if they notice any incorrect data about themself on ScholarX archive

**Describe the solution you'd like**
Implement contact us section for ScholarsX archive

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by janithlahirukariyawasam**
## Purpose

The purpose of this PR is to fix #1556 

## Goals

The Goal of this PR is to implement a mechanism to mentors/mentees to contact SEf if some of their data on the archive is incorrect.

  
### Preview Link

https://pr-1560-sef-site.surge.sh/
https://pr-1560-sef-site.surge.sh/scholarx/archive/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by janithlahirukariyawasam** [comment]
@YoshithaRathnayake any improvement ideas?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake any improvement ideas?

@anjula-sack ?

**Review by anjula-sack — CHANGES_REQUESTED** [review]
I think we better use a different image. @MethmaPeiris99 will you be able to help us here?

**Comment by MethmaPeiris99** [comment]
> I think we better use a different image. @MethmaPeiris99 will you be able to help us here?

Yes, I'll be glad to help @anjula-sack

**Comment by janithlahirukariyawasam** [comment]
> I think we better use a different image. @MethmaPeiris99 will you be able to help us here?

Thank you @MethmaPeiris99 for the image. @anjula-sack I did some small improvement to the **show-all** button also.

**Review by Piumal1999 — APPROVED** [review]
Looks good to me

**Review by YoshithaRathnayake — APPROVED** [review]

**Comment by YoshithaRathnayake** [comment]
Looks good for me too! @janithlahirukariyawasam

**Review by anjula-sack — APPROVED** [review]
Looks good! @janithlahirukariyawasam

**Pull request merged**
