### PR TITLE
Remove google button from the footer

### LINKED ISSUE #771: Remove google button from the footer
**Describe the bug**
there is a google button in the footer linked with SEF email and its irrelevant. remove it.

**To Reproduce**
1. Go to Home Page
3. Scroll down to the Footer

**Expected behavior**
Google button should not be in the footer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Version Version 85.0.4183.83 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Madhawa97**
## Purpose

The purpose of this PR is to fix #771 

## Goals

Remove irrelevant button from the footer 
## Approach

Remove Google Icon from the footer.

### Screenshots

image
 
 
### Preview Link

https://pr-772-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Test environment

Windows 10

### CODE REVIEW

**Review by jayasanka-sack — APPROVED** [review]
Thanks @Madhawa97! 😇

**Comment by Piumal1999** [comment]
Shall we change the icon to a mail icon instead of removing it? @jayasanka-sack wdyt?

**Comment by jayasanka-sack** [comment]
> Shall we change the icon to a mail icon instead of removing it? @jayasanka-sack wdyt?

Akshika asked to remove it completely. We need to find some other way to provide the email

**Review by Piumal1999 — APPROVED** [review]

**Comment by Piumal1999** [comment]
> > Shall we change the icon to a mail icon instead of removing it? @jayasanka-sack wdyt?
> 
> Akshika asked to remove it completely. We need to find some other way to provide the email

Then it's alright. Approved

**Pull request merged**
