### PR TITLE
Create faq in examples

### PR DESCRIPTION
**Pull request by Gravewalker666**

### CODE REVIEW

**Comment by Gravewalker666** [comment]
image

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Remove faq.html and add this to components.html

**Comment by Gravewalker666** [comment]
Ok

**Comment by Gravewalker666** [comment]
Done! @jayasanka-sack

**Review by jayasanka-sack — APPROVED** [review]

**Comment by jayasanka-sack** [comment]
#269

**Pull request merged**
