### PR TITLE
Changed the footer to 2021

### PR DESCRIPTION
**Pull request by aditya28sarin**
## Purpose

The purpose of this PR is to fix #<issue-number>

### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gimhan-minion — APPROVED** [review]
Thank you @aditya28sarin. This seems fine. Would you mind updating your pull request description? You can refer to merged PR's to understand how it should be done.

**Comment by Piumal1999** [comment]
Good job @aditya28sarin 
Btw, shall we add a javascript script instead of hardcoding the year? @Gimhan-minion @aditya28sarin

**Comment by Gimhan-minion** [comment]
> Good job @aditya28sarin
> Btw, shall we add a javascript script instead of hardcoding the year? @Gimhan-minion @aditya28sarin

Yeah, this seems like a solid solution rather than renaming it every year. Can you work on that @aditya28sarin? :hugs:

**Comment by aditya28sarin** [comment]
Yes, sure I will add the JS and create another pull request

**Comment by janethavi** [comment]
@aditya28sarin You can update this same PR(Pull Request) by pushing another commit to the same branch which contains the JS code.

**Comment by Gimhan-minion** [comment]
Sorry, @aditya28sarin we'll close this PR since there wasn't any response from you. You can always contribute to our community. Thank you.

**Pull request closed without merging**
