### PR TITLE
Link the OneLive page's 'Learn more' button to FAQ section

### LINKED ISSUE #714: Onelive page hero section button is not working
**Describe the bug**
Onelive page hero section button is not working

**To Reproduce**
1. Go to 'https://sefglobal.org/onelive/'
2. Click on 'Learn more' button
3. See error

**Expected behavior**
Redirecting to past onelives section

**Screenshots**
OneLive_Sustainable_Education_Foundation_-_2020-06-11_00 45 24

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.04
 - Browser [e.g. chrome, safari] Google Chrome

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Piumal1999**
## Purpose

The purpose of this PR is to fix #714 

## Goals

Fix the "Learn more" button on onelive page

## Approach

Added an id for past onelives section

### Screenshots

N/A

### Preview Link

https://pr-716-sef-site.surge.sh/onelive/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
Ubuntu 19.04
Google Chrome

## Learning

N/A

### CODE REVIEW

**Review by anjula-sack — DISMISSED** [review]
Thank You! @Piumal1999

**Review by jayasanka-sack — DISMISSED** [review]
It's better if we could point it to the FAQ section.
https://sef.discourse.group/t/displaying-past-onelives-on-the-website/18/45?u=jaye

Instead of using "Fix" on the commit message use a specific one. 
Ex: "Link the OneLive page's 'Learn more' button to FAQ section"

**Comment by Piumal1999** [comment]
> It's better if we could point it to the FAQ section.
> https://sef.discourse.group/t/displaying-past-onelives-on-the-website/18/45?u=jaye
> 
> Instead of using "Fix" on the commit message use a specific one.
> Ex: "Link the OneLive page's 'Learn more' button to FAQ section"

Yeah. I updated that.
Thanks!

**Review by anjula-sack — APPROVED** [review]

**Review by jayasanka-sack — APPROVED** [review]
Thanks @Piumal1999 !

**Pull request merged**
