### PR TITLE
Change the profiles section of ScholarX, Onelive and IRC pages

### LINKED ISSUE #976: Profiles section of Scholarx, IRC and Team pages does not scroll up when "SEE LESS" button is clicked
**Describe the bug**
A "SEE LESS" button was implemented recently to the profiles sections of Scholarx,IRC and Team pages. However once the "SEE LESS" button is clicked, the page does not scroll up to the former profile section view, instead it remains at the lower end of the page in the "Frequently Asked Questions" section(or lower), which removes the profiles section from view.

**To Reproduce**
1. Go to [OneLive page](https://sefglobal.org/onelive/)
2. Scroll down to the profiles section
3. Click on the "SEE MORE" button
4. Scroll further down until you see the "SEE LESS" button, and click on it
5. Observe that the profiles section is out of view and the page is at "Frequently Asked Questions" section or lower.

**Expected behavior**
Once the "SHOW LESS" button is clicked, the view should scroll up to it's original profile section view

**Screenshots**
Once the "SEE MORE" button is clicked(Original view)
image
Once the "SEE LESS" button is clicked
image

**Desktop:**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [91.0.4472.114 (Official Build) (64-bit)]

**Additional context**
An event listener to the "SEE LESS" button, which would reference back to the h1 tag would suffice to solve this issue.

### PR DESCRIPTION
**Pull request by miniskynet**
## Purpose

This PR fixes #976 
The three provided links all contain profiles sections with a "SEE LESS" button. Once the button is clicked the page does not scroll up to the former profile section view, instead it remains at the lower end of the page in the "Frequently Asked Questions" section(or lower), which removes the profiles section from view. A functionality had to be implemented in-order for the profiles section to scroll back to it's original position once the "SEE LESS' button is clicked.

OneLive - [https://sefglobal.org/onelive/](url)
ScholarX - [https://sefglobal.org/scholarx/2021/](url)
International Research Council - [https://sefglobal.org/irc.html](url)

## Goals

Adding an ID to the div section of each profile section, and assigning a hyperlink reference tag to the "SEE LESS" button will solve this issue. 

## Approach

*Find profile div sections in OneLive, ScholarX and IRC pages respectively. 
*Assign ID's to each profile div section.
*Change the "SEE LESS" `button` tag to `a` tag in each page.
*Add `href` tags and reference the ids of the profile div sections respectively. 

### Screenshots

**Original profiles section after expansion :** 

original_expanded

**Original profiles section after contraction :**

original_contracted

**New profiles section after contraction(Scrolls back to original view):**

new_contracted

### Preview Link

https://pr-983-sef-site.surge.sh/

##  Checklist
- This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation

## Related PRs
 
none

## Test environment
 
**OS :**
Edition	Windows 10 Home
Version	20H2
Installed on	‎5/‎3/‎2021
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Java:**
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Browser:**
Google Chrome
Version 91.0.4472.114 (Official Build) (64-bit)

## Learning

none

### CODE REVIEW

**Review by Gravewalker666 — APPROVED** [review]
Look good to me @miniskynet 
Can you please update the preview link and change the commit message and pr title to be in the imperative mood?
ref: https://chris.beams.io/posts/git-commit/#imperative

**Comment by miniskynet** [comment]
@Gravewalker666 hey I changed the PR title, and the commit message to imperative(using `amend` and `force push`). The commit message however seems to be broken into two sections as topic and body. I don't know how that happened. Also I changed the preview link to match the PR number, which also does not seem to load. Can you please be kind enough to take a look?
Thank you :)

**Review by Gravewalker666 — APPROVED** [review]
Thank you @miniskynet 
Sorry for the delay,
I'll squash and merge the PR but from next time let's try to make only one commit per one PR 🙂

**Comment by miniskynet** [comment]
@Gravewalker666  no worries :) 
I was not aware of the imperative format, so I'll try to keep that in mind for next time.

**Pull request merged**
