### PR TITLE
Fix responsiveness of logo sections

### LINKED ISSUE #722: Fix the mobile view of "Our mentors are from" section
**Describe the bug**
"Our mentors are from" section on the landing page is not displaying properly in mobile view

**To Reproduce**
1. Go to 'https://sefglobal.org' on mobile view
2. Scroll down to 'Our mentors and speakers are from' section
3. See error

**Expected behavior**
Display 2 logos per row

**Screenshots**
IMG_20200616_030627

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: Android 10
 - Browser Google Chrome

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Piumal1999**
## Purpose

The purpose of this PR is to fix #722

## Goals

Fix the responsiveness of "our mentors are from section" and  "press coverage" section

## Approach

Fixed the mobile view
Removed hover effect on "our mentors are from" section
Reduced the size of press coverage logos

### Screenshots

Home_Sustainable_Education_Foundation_-_2020-06-19_01 51 00

Mobile view:

IMG_20200619_020503

IMG_20200619_020516

### Preview Link

https://pr-721-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
#702 

## Test environment
 
Ubuntu 19.04
Google Chrome

Pocophone F1 
Android 10
Google Chorme

## Learning

N/A

### CODE REVIEW

**Comment by anjula-sack** [comment]
I think "Press coverage" logos are a little bit bigger. WDYT @jayasanka-sack @Piumal1999

**Review by anjula-sack — APPROVED** [review]
Awesome! @Piumal1999

**Review by jayasanka-sack — APPROVED** [review]
Thanks @Piumal1999 !

**Comment by Piumal1999** [comment]
Fix #722

**Pull request merged**
