### PR TITLE
Fix the bugs in the footer in the mobile view

### LINKED ISSUE #1207: Fix the bugs in the footer in the mobile view
**Describe the bug**
Currently, the footer of the sef-site in the resolution ( Mobile View < 991 )

**To Reproduce**
1. Go to [SEF-SITE](https://www.sefglobal.org)
3. Scroll down to 'Footer'

**Expected behavior**
Fix the bugs in the footer in the resolution ( Mobile View < 991 )

**Screenshots**

image

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #1207 

## Goals

Fixing the bugs in the footer in the mobile view

## Approach

I fixed the bugs in the footer in the mobile view

### Screenshots

> At the resolution < 991

Before

image

After

image

> At the resolution < 458

Before

image

After

image

  
### Preview Link

https://pr-1209-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Show the year and SEF part at the bottom after the footer.

**Comment by YoshithaRathnayake** [comment]
> Show the year and SEF part at the bottom after the footer.

**Comment by anjula-sack** [comment]
@YoshithaRathnayake Any updates on this?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Any updates on this?

Nope forgot to remove the draft @anjula-sack

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Now the desktop view is messed up. 
image

**Comment by YoshithaRathnayake** [comment]
Ok @anjula-sack done!

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Still different 
image

**Comment by Piumal1999** [comment]
It will be easier if we use bootstrap classes instead of writing css media queries for every edge case.

**Comment by YoshithaRathnayake** [comment]
> It will be easier if we use bootstrap classes instead of writing css media queries for every edge case.

Yes I am thinking to undo this changes and redo them with the changes requested. Is it ok @Piumal1999 , @anjula-sack

**Comment by anjula-sack** [comment]
> > It will be easier if we use bootstrap classes instead of writing css media queries for every edge case.
> 
> Yes I am thinking to undo this changes and redo them with the changes requested. Is it ok @Piumal1999 , @anjula-sack

sure, I'll make this draft until that.

**Comment by YoshithaRathnayake** [comment]
> > > It will be easier if we use bootstrap classes instead of writing css media queries for every edge case.
> > 
> > 
> > Yes I am thinking to undo this changes and redo them with the changes requested. Is it ok @Piumal1999 , @anjula-sack
> 
> sure, I'll make this draft until that.

so I think to close this pr and do this again with bootstrap. Is it ok @anjula-sack

**Comment by anjula-sack** [comment]
> > > > It will be easier if we use bootstrap classes instead of writing css media queries for every edge case.
> > > 
> > > 
> > > Yes I am thinking to undo this changes and redo them with the changes requested. Is it ok @Piumal1999 , @anjula-sack
> > 
> > 
> > sure, I'll make this draft until that.
> 
> so I think to close this pr and do this again with bootstrap. Is it ok @anjula-sack

yeah sure no worries.

**Comment by YoshithaRathnayake** [comment]
@anjula-sack is it ok if I do this in custom css bcs I can't understand to do this in bootstrap

**Pull request closed without merging**
