### PR TITLE
Move scholarx success stories folder inside the scholax folder

### LINKED ISSUE #1275: Move scholarx success stories folder inside the scholax folder
**Is your feature request related to a problem? Please describe.**
The scholax `success-stories` folder should be inside of the scholax folder so that the url will be displayed as `https://sefglobal.org/scholarx/success-stories/`

**Describe the solution you'd like**
move the `succes-stories` folder from root to the `scholarx` folder. and update the access url on the `scholarx 2022` page

**Are you working on it?**
No. (I will invite a friend, Actually)

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #1275 

## Goals

Moving scholarx success stories folder inside the scholax folder

## Approach

Moved scholarx success stories folder inside the scholax folder

### Screenshots

image

  
### Preview Link

https://pr-1292-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
@Piumal1999 can you say a method to fix this conflicts because the resolve conflicts button is disabled, I can't click it

**Comment by Piumal1999** [comment]
> @Piumal1999 can you say a method to fix this conflicts because the resolve conflicts button is disabled, I can't click it

The button is disabled because GitHub doesn't support resolving conflicts caused by changes like file deletions, renaming etc. So the conflicts should be resolved locally. 

Since this pull request contains only a few changes, the easiest solution would be,
1. Hard reset the local branch (don't delete) `git reset --hard upstream/master`
2. Get a pull from the upstream master
3. Do the changes
4. Commit and Force push to the same branch (`success-stories-directory`)
It will automatically update the pull request.

Or you can refer to the _Removed file merge conflicts section_ of [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) if you want to try resolving the conflicts.

**Comment by YoshithaRathnayake** [comment]
> > @Piumal1999 can you say a method to fix this conflicts because the resolve conflicts button is disabled, I can't click it
> 
> The button is disabled because GitHub doesn't support resolving conflicts caused by changes like file deletions, renaming etc. So the conflicts should be resolved locally.
> 
> Since this pull request contains only a few changes, the easiest solution would be,
> 
> 1. Hard reset the local branch (don't delete) `git reset --hard upstream/master`
> 2. Get a pull from the upstream master
> 3. Do the changes
> 4. Commit and Force push to the same branch (`success-stories-directory`)
>    It will automatically update the pull request.
> 
> Or you can refer to the _Removed file merge conflicts section_ of [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) if you want to try resolving the conflicts.

Sure thanks @Piumal1999

**Comment by YoshithaRathnayake** [comment]
@Piumal1999 @anjula-sack can you see whether that problem now resolved?

**Review by anjula-sack — APPROVED** [review]
Thank you! @YoshithaRathnayake

**Pull request merged**
