### PR TITLE
Update index.html

### LINKED ISSUE #754: Incorrect heading colour in scholarx mentors section
**Describe the bug**
The heading colour of mentors section is black while other headings are in default colour.

**To Reproduce**
1. Go to 'https://sefglobal.org/scholarx/2020/'
2. Scroll down to 'mentors' section
3. See error

**Expected behavior**
Change the colour of mentors section heading to the default colour. (Use the heading colour used in other sections) 

**Screenshots**
IMG_20200825_231030

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.04
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by miniskynet**
Change "Mentors" section heading format to "Featured stories" section heading format

## Purpose
The "Mentors" section heading format and color is different from the other heading formats. Has to change the color and format used in the "Featured stories" section

## Goals
The following is line 123. 
`   <p class="display-3 text-center">Mentors</p>`
This line of code provides paragraph format instead of heading format. 

## Approach
Take reference from line 135 (used in "Featured stories" heading)
`   <h1 class="mb-5 text-center font-weight-bold">Mentors</h1>`
This line of code changes the "Mentors" section to the format used in "Featured stories"

### Screenshots
Before;
old

After:
new

  
### Preview Link

https://pr-762-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gravewalker666 — APPROVED** [review]
Thank You @miniskynet

**Comment by miniskynet** [comment]
> Thank You @miniskynet

**Comment by miniskynet** [comment]
> Thank You @miniskynet

You're welcome @Gravewalker666 :)

**Review by akshika47 — APPROVED** [review]

**Comment by akshika47** [comment]
Thank you @miniskynet

**Comment by akshika47** [comment]
@miniskynet don't close the PR until it is reviewed. An admin will review the PR and merge it. Then it will be closed. 

@Gravewalker666 could you merge this PR?

**Comment by Gravewalker666** [comment]
> @miniskynet don't close the PR until it is reviewed. An admin will review the PR and merge it. Then it will be closed.
> 
> @Gravewalker666 could you merge this PR?

Yeah Sure!!

**Pull request merged**
