### PR TITLE
Create a section to view featured stories of scholarx 2020

### LINKED ISSUE #540: Create a card to add blog posts.
**Is your feature request related to a problem? Please describe.**
- There are going to be a new section with featured stories (from past year) 

**Describe the solution you'd like**
- Create a new section below faq's for mentees.
- Add "Featured Stories" as the title
- Create a new card
- Add card to the section
- Use this as a dummy content
https://blog.sefglobal.org/2019/11/scholarx-class-of-2019-sx19/

- The design should be something like this.
Screenshot from 2020-02-28 15-17-12

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jayasanka-sack**
## Purpose

The purpose is to fix #540 

## Goals

- Create a card to display featured stories
- Render posts dynamically

## Approach

- Create a card
- Create a json file to featured stories
- Render them from the json file
- Add load more button (it loads first 6 posts, loads the rest when clicking the load mor ebutton )

### Screenshots

Screenshot 2020-02-29 at 14 37 48

### Preview Link

https://pr-552-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Learning

http://coenraets.org/blog/2011/12/tutorial-html-templates-with-mustache-js/

### CODE REVIEW

**Comment by anjula-sack** [comment]
Each card should have same size. @jayasanka-sack

**Comment by jayasanka-sack** [comment]
> Each card should have same size. @jayasanka-sack

Sure, let me try to find a solution. It occurs with the titles

**Comment by jayasanka-sack** [comment]
@anjula-sack fixed

**Review by anjula-sack — APPROVED** [review]
Good Job!

**Pull request merged**
