### PR TITLE
Replace ScholarX 2019 mentees images with Cloudinary URLs

### LINKED ISSUE #1047: Replace ScholarX 2019 mentee's images with Cloudinary URLs
**Is your feature request related to a problem? Please describe.**
Use Cloudinary image hosting service to import images to the page

**Describe the solution you'd like**
1. Use the below image URLs to update the image column in the google sheet

```
v1625396001/ScholarX_Mentees/2019/savindi_ailiwm.jpg
v1625396001/ScholarX_Mentees/2019/tarinduj_msadmq.jpg
v1625396000/ScholarX_Mentees/2019/najma_g1gpmt.jpg
v1625396000/ScholarX_Mentees/2019/ramith_kwcjq9.jpg
v1625396000/ScholarX_Mentees/2019/nadiya_rz1fkr.jpg
v1625396000/ScholarX_Mentees/2019/nadeeshang_wnpapr.jpg
v1625395999/ScholarX_Mentees/2019/mohamedafh_hd5up3.jpg
v1625395999/ScholarX_Mentees/2019/mohameda_y4gpk2.jpg
v1625395999/ScholarX_Mentees/2019/matheesha_nssglp.jpg
v1625395999/ScholarX_Mentees/2019/maleplaceholder_p86qg7.jpg
v1625395999/ScholarX_Mentees/2019/insaf_evynwe.jpg
v1625395999/ScholarX_Mentees/2019/janidu_xagrdf.jpg
v1625395999/ScholarX_Mentees/2019/hasinis_f27cil.jpg
v1625395998/ScholarX_Mentees/2019/kithminih_mlsy38.jpg
v1625395998/ScholarX_Mentees/2019/dohitha_qg8aak.jpg
v1625395998/ScholarX_Mentees/2019/gallage_qq9hbm.jpg
v1625395998/ScholarX_Mentees/2019/haritha_wgxzkf.jpg
v1625395998/ScholarX_Mentees/2019/chathurad_mojz5o.jpg
v1625395998/ScholarX_Mentees/2019/chamikas_r8m6de.jpg
v1625395998/ScholarX_Mentees/2019/adhisha_lg8ern.jpg
```
google sheet link- 
https://docs.google.com/spreadsheets/d/1hD77jQc9kohGfX1QpERumwcjTRK1EOHk8AKd2I9e2mg/edit?usp=sharing

2. Replace `images/mentees/{{image}}` with `https://res.cloudinary.com/dsxobn1ln/image/upload/c_scale,h_48,w_48/{{image}}` in the scholarx/archive/2019/index.html

### PR DESCRIPTION
**Pull request by akeel230**
## Purpose
Replace ScholarX 2019 mentor's images with Cloudinary URLs fix #1047 

## Goals
Replace ScholarX 2019 mentor's images with Cloudinary URLs

## Approach
Copy image URLs in issue #1047  to spreadsheet and update link in index.html

### Preview Link

https://pr-1051-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
#1041
#1042
#1045

### CODE REVIEW

**Review by Piumal1999 — COMMENTED** [review]
Good job @akeel230
Next time reset the branch and get a pull from upstream before start working on the issue(or just use new branches for each Pull Request). So you can prevent getting commits like `Merge branch 'master' of....`

**Comment by akeel230** [comment]
@Piumal1999 yes , sorry and it wort happen again

**Comment by akeel230** [comment]
@Piumal1999 shall I close this and redo the changes? or is it ok for this time?

**Comment by Piumal1999** [comment]
> @Piumal1999 shall I close this and redo the changes? or is it ok for this time?

It's ok for now since we use squash and merge option.

**Review by Gravewalker666 — APPROVED** [review]

**Pull request merged**
