### PR TITLE
Re adjust the readme logo and link

### LINKED ISSUE #1297: ReadMe.LK link on press coverage section is not working
**Describe the bug**
The ReadME.lk post about SEF is no longer there. The link redirects to a 404 error page.

image

image

**To Reproduce**
1. Go to Homepage
2. Go to `Press Coverage` section
3. Click on `README.lk` logo

**Expected behavior**
N/A

**Additional context**
N/A

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by RandilaP**
## Purpose

The purpose of this PR is to fix #1297 

## Goals
- Add the readme logo and it's new link

### Screenshots
image

### CODE REVIEW

**Comment by RandilaP** [comment]
@anjula-sack @jayasanka-sack @Piumal1999 @kumuditha-udayanga Can you review this

**Review by kumuditha-udayanga — DISMISSED** [review]
LGTM, what do you think @anjula-sack @Piumal1999 ?

**Comment by Piumal1999** [comment]
There's a small alignment issue with the logo. This is the logo we used earlier -> https://github.com/sef-global/sef-site/blob/2ea4c351c46574ed54f55c4836d4fc6c0e5de274/assets/img/logos/readme.png

PS: Just found out that they had changed their logo. (https://readme.lk/readme-style-guide/#). Let's use the new logo

**Review by Piumal1999 — APPROVED** [review]
Thank you @RandilaP 
Next time, please include the preview link in the pull request description.
(`https://pr-PRNumber-sef-site.surge.sh`)

Example:
https://pr-1315-sef-site.surge.sh

**Pull request merged**
