### PR TITLE
Update the scholarX 2022 featured stories

### LINKED ISSUE #1381: Update the scholarX 2022 featured stories
**Is your feature request related to a problem? Please describe.**
We need to update the scholarX 2022 featured stories

**Describe the solution you'd like**
Replace the following places,
1. Update the script link: https://github.com/sef-global/sef-site/blob/80c92f4bdf2e6cdcdf1a68afa972af17328d751a/scholarx/2022/functions.js#L33 

with `https://script.google.com/macros/s/AKfycbxoEfCuQK2x57cHG0HG0YlljD6FoKbIwygdEz0wkt6ex4YAxEviuLdwJbiXKNZwA-k64g/exec`

2. Update the author image link: https://github.com/sef-global/sef-site/blob/2dcf6276cfebefec29fa9232eb671069954b35c2/scholarx/2022/index.html#L674 
with `https://res.cloudinary.com/dsxobn1ln/image/upload/c_scale,h_200,w_200/{{author_image}}`

3. Update the blog image link: https://github.com/sef-global/sef-site/blob/2dcf6276cfebefec29fa9232eb671069954b35c2/scholarx/2022/index.html#L667 
with `https://res.cloudinary.com/dsxobn1ln/image/upload/c_scale,w_400/{{image}}`

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #1381 

## Goals

Updating the scholarX 2022 featured stories

## Approach

Updated the scholarX 2022 featured stories

### Screenshots

image
image
image

  
### Preview Link

https://pr-1382-sef-site.surge.sh/scholarx/2022

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
@anjula-sack @jayasanka-sack @Piumal1999  how about this?

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Good job! @YoshithaRathnayake can you remove the featured stories images directory?https://github.com/sef-global/sef-site/tree/master/scholarx/2022/images/featured-stories

**Comment by YoshithaRathnayake** [comment]
> Good job! @YoshithaRathnayake can you remove the featured stories images directory?https://github.com/sef-global/sef-site/tree/master/scholarx/2022/images/featured-stories

Done! @anjula-sack

**Review by anjula-sack — APPROVED** [review]
Thank you! @YoshithaRathnayake

**Pull request merged**
