### PR TITLE
Change position of FAQ section in irc.html

### LINKED ISSUE #738: Move the FAQ section to the section after Researchers' section in IRC page
**Is your feature request related to a problem? Please describe.**
In the IRC page, FAQ section is just after the hero image.

**Describe the solution you'd like**
FAQ section in the IRC pages needs to move below the researcher's section.(i.e. swap the place of FAQ and Researchers section)

### PR DESCRIPTION
**Pull request by Gimhan-minion**
## Purpose
The purpose of this PR is to fix #738 

## Goals
To change the order of researchers section and FAQ section in irc.html 

## Approach
Switched sections in irc.html file
  
### Preview Link

https://pr-741-sef-site.surge.sh/irc.html

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Piumal1999 — DISMISSED** [review]

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
Isn't it consistent if we use background colours in this way?
image

**Comment by Gimhan-minion** [comment]
> Isn't it consistent if we use background colours in this way?
> image

Should I remove the background color in "Researchers" section? @Gravewalker666 @akshika47

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
- Let's add a margin after this show more button
image

**Review by Gravewalker666 — APPROVED** [review]
Beautiful Mate! Well done @Gimhan-minion , Ready to merge!

**Review by anjula-sack — APPROVED** [review]
Awesome! @Gimhan-minion

**Pull request merged**
