### PR TITLE
Update the team page

### LINKED ISSUE #784: Update the team page
**Is your feature request related to a problem? Please describe.**
- We need to update the team page little bit.

**Describe the solution you'd like**
 Move below names to the Alumni section
- Nimesh Ekanayake
- Francisco Hettige Cristian Silva
- Thavarasa Vithusan
- Tharika Weerakoon

Add below names under the Executive committee 
- Viraj C. Kirinda - Program Manager
- Promodini Jayakodi - Assitant Program Manager
- Aathil Ahamed - Assitant Program Manager
- Shreeharan Hareendran - Digital Marketing Executive
Use LinkedIn images for the profile image

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #784

## Goals

- Keep the team page updated 
## Approach

- Moved given names Alumni section
- Added new name to the e]Executive Committee section 
- Removed the hero image 
### Screenshots

image

### Preview Link

https://pr-785-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by jayasanka-sack — DISMISSED** [review]
Thanks @anjula-sack !

No issues in codings. But i didn't validate the data.

**Review by Gimhan-minion — DISMISSED** [review]
@anjula-sack Can you remove the images of the profiles which are removed :hugs:

**Review by Gimhan-minion — COMMENTED** [review]
One more thing. "Aathil Ahamed"s image doesn't match with the rest. It's better if we change that image too. WDYT @jayasanka-sack?

**Comment by akshika47** [comment]
People are removed should move to the Alumni

**Comment by anjula-sack** [comment]
> @anjula-sack Can you remove the images of the profiles which are removed 🤗

I didn’t remove any profiles. Those profiles are moved to the Alumni section @Gimhan-minion

**Comment by anjula-sack** [comment]
> One more thing. "Aathil Ahamed"s image doesn't match with the rest. It's better if we change that image too. WDYT @jayasanka-sack?

I couldn’t find his image without it, so I asked him to send me and @akshika47 asked me to remove the hero image as well. @Gimhan-minion

**Comment by Gimhan-minion** [comment]
> > @anjula-sack Can you remove the images of the profiles which are removed hugs
> 
> I didn’t remove any profiles. Those profiles are moved to the Alumni section @Gimhan-minion

Noted :100::heart:

**Review by Gimhan-minion — APPROVED** [review]
Thank you @anjula-sack :100:

**Review by jayasanka-sack — APPROVED** [review]

**Comment by akshika47** [comment]
@anjula-sack ! I know the PR is closed, but I assume you would change Aathil's photo when you do remove the top section on the team's page as well. When I meant to remove the Hero image, I meant the entire section. Sorry about the miscommunication.

**Pull request merged**
