### PR TITLE
Change word from "Upspeak" to "UpSpeak" 

### LINKED ISSUE #991: Fix formating in the project menu Upspeak option
**Describe the bug**
In the project list on the navigation bar, there is a project called `Upspeak`. The formatting should be similar to the logo. This small error can be found on the [UpSpeak](https://sefglobal.org/upspeak/) page title too.

**To Reproduce**
1. Go to [https://sefglobal.org/](https://sefglobal.org/)
2. Click on the Projects menu from the navigation bar.
3. See the option `Upspeak`

**Expected behavior**
`Upspeak` should be corrected to `UpSpeak`. The reason is, in the UpSpeak logo, we have followed this format. The correction should be done in the menu as well as in the page title.

### PR DESCRIPTION
**Pull request by miniskynet**
## Purpose

The purpose of this PR is to fix #991 

## Goals

The goal of this solution is to change the formatting of the word from "Upspeak" to "UpSpeak" in the navigation bar projects list, as well the title of the "UpSpeak" page. 

## Approach

1. Edited the index.html file (of UpSpeak folder) and changed the title from "Upspeak" to "UpSpeak"
2. Edited navbar.html (inside the following path : \assets\content\static) by changing the project formatting of "Upspeak" to "UpSpeak" in the "Projects" dropdown list.

### Screenshots

**Original dropdown list :** 

droplist_original

**Post edit dropdown list :** 

droplist_edited

**Original title :** 

title_original

**Post edit title :** 

title_edited

### Preview Link

https://pr-{1000}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 
none

## Test environment
 
**OS :**
Edition	Windows 10 Home
Version	20H2
Installed on	‎5/‎3/‎2021
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Java:**
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Browser:**
Google Chrome
Version 91.0.4472.114 (Official Build) (64-bit)

## Learning

none

### CODE REVIEW

**Review by janethavi — APPROVED** [review]
Great work @miniskynet!

**Comment by janethavi** [comment]
A small thing in the PR template, when you check the checkbox you need to type an `x` inside the box so it would like `[x]`.

**Comment by miniskynet** [comment]
@janethavi Thank you :)
And I'm sorry about the checkboxes. I edited it, can you please take a look? 
Will make sure not to make that mistake again.

**Comment by janethavi** [comment]
Thank you very much @miniskynet

**Comment by miniskynet** [comment]
Hello @janethavi will this branch be merged in the future or is it an automated process? 
because I have got the following error:
image

**Comment by janethavi** [comment]
Hi @miniskynet, Don't worry about that. It happed because of an issue with our preview generator. It's now fixed.

**Comment by miniskynet** [comment]
Hello @janethavi that's great to hear :) 
I'll move onto another issue now. Thank you for the help.

**Pull request merged**
