### PR TITLE
Add New Mentors

### LINKED ISSUE #842: Update Mentors
**Is your feature request related to a problem? Please describe.**
Well, We have to update the ScholarX website with the new set of Mentors.

**Describe the solution you'd like**
Add all the new mentors to the website.

### PR DESCRIPTION
**Pull request by NaviRocker**
## Purpose

The purpose of this PR is to fix #842 

## Goals

Goal is to update all the new Mentors
### Preview Link

https://pr-843-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
Google Chrome, Windows 8.1

### CODE REVIEW

**Review by anjula-sack — APPROVED** [review]
Thank you! @NaviRocker

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Thanks for getting this done, @NaviRocker ! 

One minor request; can you fix the commit message and the PR title?

**Comment by NaviRocker** [comment]
@jayasanka-sack What's wrong with the commit message?

**Comment by jayasanka-sack** [comment]
> @jayasanka-sack What's wrong with the commit message?

Oh sorry, I forgot to mention it. 

Let's use the imperative mode. 

ex: "Update mentors" Or (Update ScholarX 2021 mentors)

**Comment by jayasanka-sack** [comment]
This is a nice guide: https://chris.beams.io/posts/git-commit/#imperative

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
image

@NaviRocker Let's crop this image to the default picture size

And there are some duplicate images. could you please recheck it?

**Pull request closed without merging**
