### PR TITLE
Fix navbar and footer links to function on pages inside directories

### LINKED ISSUE #710: Navbar and Footer links not working properly in onelive/scholarx pages
**Describe the bug**
On scholarX page and onelive page, navbar links are not working properly

**To Reproduce**

> 1. Go to 'ScholarX page'/'Onelive Page'
> 2. Click on the SEF Logo on the navbar
> 3. See error (It refreshes the same page instead of going to the homepage)

> 1. Go to 'ScholarX page'/'Onelive Page'
> 2. Click on " Sustainable Education Foundation - SEF" link
> 3. See error (It refreshes the same page instead of going to the homepage)

**Expected behavior**
Corrected links on navbar and footer

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.04
 - Browser [e.g. chrome, safari] Google Chrome

**Additional context**
I'm working on this issue

### PR DESCRIPTION
**Pull request by Piumal1999**
## Purpose

The purpose of this PR is to fix #710 

## Goals

Fix the issue with link on navbar and footer

## Approach

Corrected the links

### Screenshots

 N/A
### Preview Link

https://pr-711-sef-site.surge.sh/onelive/
https://pr-711-sef-site.surge.sh/scholarx/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
Ubuntu 19.04
Google Chrome

## Learning

N/A

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
The commit message and title are too generic. Shall we make it more specific?

**Review by jayasanka-sack — DISMISSED** [review]
Thanks for fixing this @Piumal1999 !

The commit message and title are too generic. Shall we make it more specific?

**Comment by Piumal1999** [comment]
> Thanks for fixing this @Piumal1999 !
> 
> The commit message and title are too generic. Shall we make it more specific?

Something like this? @jayasanka-sack
"Fix navbar and footer links to function on pages inside directories"

**Review by Gravewalker666 — APPROVED** [review]
Good job @Piumal1999

**Review by anjula-sack — APPROVED** [review]
Great! @Piumal1999

**Pull request merged**
