### PR TITLE
Add suitable icons for navbar

### LINKED ISSUE #457: Add suitable icons for navbar on mobile view
**Is your feature request related to a problem? Please describe.**
Same icon is used for 5 links in the navbar on mobile view.

Current view:
IMG_20200125_232056

**Describe the solution you'd like**
Replace the icons relative to the link.

**Describe alternatives you've considered**
N/A

**Additional context**
Navbar path: assets/content/static/navbar.html

### PR DESCRIPTION
**Pull request by yozaam**
## Purpose

The purpose of this PR is to fix #457<issue-number>

## Goals

Using icons from the font-awesome icons collection
## Approach

changing the class names, as described here, https://github.com/sef-global/sef-site/issues/457#issuecomment-578433504
### Screenshots

  
Screenshot 2020-01-26 at 7 13 57 PM

### Preview Link

https://pr-463-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [X] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

## Learning

Font Awesome library,

### CODE REVIEW

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
Wow! Neatly Done mate!
Nice job.
Can you please add the surge review link?
just replace the PR number

**Comment by Gravewalker666** [comment]
And just add the icons for mobile view. Keep the desktop view as it is now.

**Comment by yozaam** [comment]
Okay, I'll remove it from desktop and edit the surge , thanks, I love the way your organisation works with the friendly emails and conversation 😄

**Review by Gravewalker666 — APPROVED** [review]
We are so glad to know that you guys feel friendly and safe in our community.
Thank you for being a part of it Lad!
BTW be more descriptive with your commit messages. The way you set commit messages is not quite up to the standard level.
Use something that describes the change that you have done/
- https://chris.beams.io/posts/git-commit/ Read this post and get an insight
Cheers!

**Pull request merged**
