### PR TITLE
Fix inconsistencies in readme.md

### LINKED ISSUE #734: Inconsistent style of Run Local in readme.md
**Describe the bug**
The command highlights the commands differently for npm start 

**Expected behavior**
same style as npm install

**Screenshots**

Screenshot 2020-07-06 at 9 57 28 PM

 - github readme.md

### PR DESCRIPTION
**Pull request by yozaam**
## Purpose
The purpose of this PR is to fix #734  style of readme.md for npm start

## Goals
Improve Consistency on readme file

## Approach

Changed inline highlight to block hightlight

### Screenshots
Screenshot 2020-07-07 at 12 33 30 PM
  
### Preview Link
https://pr-736-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
NA

## Test environment
preview on github fork

## Learning
Markdown syntax for inline code is ' but block is '''

### CODE REVIEW

**Comment by yozaam** [comment]
Hi @Piumal1999 could you approve it?

**Comment by Piumal1999** [comment]
Awesome @yozaam !! 
Before we merge the PR could you please fill the description according to the pull request template. You can find it from this link (https://github.com/sef-global/sef-site/blob/master/pull_request_template.md)

**Comment by yozaam** [comment]
Oh so sorry, of course

**Comment by Piumal1999** [comment]
And also let's change the pull request title to something like this "Fix inconsistencies in readme.md "

**Review by Piumal1999 — APPROVED** [review]
Well done!! @yozaam 
Thanks for contributing

**Review by Gimhan-minion — APPROVED** [review]
Thank you @yozaam

**Pull request merged**
