### PR TITLE
Replace IRC Researcher's images with Cloudinary URLs

### LINKED ISSUE #1002: Replace IRC Researcher's images with Cloudinary URLs
**Is your feature request related to a problem? Please describe.**
Use Cloudinary image hosting  service to import images to the researcher's section on the IRC page  

**Describe the solution you'd like**
1. Use the below image URLs to update the image column in the google sheet

```
v1625329125/IRC_Researchers%20/upeka_somarathne_hjaewi.jpg
v1625329130/IRC_Researchers%20/kajeenthan_kamalaseelan_kujhri.jpg
v1625329137/IRC_Researchers%20/rasika_dissanayake_cs1lfn.jpg
v1625329142/IRC_Researchers%20/lasara_kariyawasam_bkkr4u.jpg
v1625329155/IRC_Researchers%20/durga_dharmadana_og7i3b.jpg
v1625329163/IRC_Researchers%20/upekha_miriyagalla_xalgrq.jpg
v1625329168/IRC_Researchers%20/biyanka_ekanayake_iuixcf.jpg
v1625329172/IRC_Researchers%20/pevindu_abeysinghe_l1d9k5.jpg
v1625329176/IRC_Researchers%20/udani_wijewardhana_apmbby.jpg
v1625329194/IRC_Researchers%20/sumudu_mal_izcagp.jpg
v1625329205/IRC_Researchers%20/arosha_kzn4xk.jpg
v1625329210/IRC_Researchers%20/chamindie_l7uibe.jpg
v1625329322/IRC_Researchers%20/gathsaurie_pxqnsv.jpg
v1625329326/IRC_Researchers%20/sachith_bsnjpl.jpg
v1625329345/IRC_Researchers%20/chamod_eejfcc.jpg
v1625329351/IRC_Researchers%20/chathura_c6qgsy.jpg
v1625329365/IRC_Researchers%20/hasini_g2s2ma.jpg
v1625329372/IRC_Researchers%20/kalhari_ghprom.jpg
v1625329377/IRC_Researchers%20/thisum_h2z0b9.jpg
v1625329390/IRC_Researchers%20/suren_iebj6w.jpg
v1625329442/IRC_Researchers%20/priyadharshany_ozmmbl.jpg
v1625329451/IRC_Researchers%20/pramodh_bmaw7r.jpg
v1625329462/IRC_Researchers%20/sumali_atglrs.jpg
v1625329467/IRC_Researchers%20/nadeera_xazelv.jpg
v1625329489/IRC_Researchers%20/nilushka_khmlie.jpg
v1625329496/IRC_Researchers%20/ashan_byecqa.jpg
v1625329501/IRC_Researchers%20/sajith_fuimsc.jpg
v1625329510/IRC_Researchers%20/mirantha_alupbz.jpg
v1625329532/IRC_Researchers%20/nivanthika_fwefbn.jpg
v1625329539/IRC_Researchers%20/ruwandi_vkszeo.jpg
v1625329544/IRC_Researchers%20/naresh_q7cet7.jpg
v1625329549/IRC_Researchers%20/vishvapali_ba2uac.jpg
v1625329561/IRC_Researchers%20/dakshitha_tutnv3.jpg
v1625329569/IRC_Researchers%20/dinithi_eaetph.jpg
v1625329573/IRC_Researchers%20/iroshan_tqkhms.jpg
v1625329580/IRC_Researchers%20/yomani_vud25e.jpg
v1625329593/IRC_Researchers%20/sohani_igzmpr.jpg
v1625329598/IRC_Researchers%20/gamalendira_z9pksk.jpg
v1625329605/IRC_Researchers%20/gayani_ph04rl.jpg
v1625329615/IRC_Researchers%20/prasangi_x06kea.jpg
v1625329623/IRC_Researchers%20/nirupama_hbbznc.jpg
v1625329630/IRC_Researchers%20/chandima_cqlmkl.jpg
v1625329642/IRC_Researchers%20/chirath_soap9v.jpg
v1625329647/IRC_Researchers%20/janindu_progfv.jpg
v1625329657/IRC_Researchers%20/krishani_ys2csx.jpg
v1625329669/IRC_Researchers%20/sitara_chg81t.jpg
v1625329674/IRC_Researchers%20/mahendrini_hjo1kk.jpg
v1625329678/IRC_Researchers%20/zahra_jvf6dm.jpg
v1625329685/IRC_Researchers%20/lasith_vrgkrj.jpg
v1625329689/IRC_Researchers%20/madhuranga_eojw4c.jpg
v1625329693/IRC_Researchers%20/rakshitha_hftrv2.jpg
v1625329700/IRC_Researchers%20/heshanaravinda_iuiqgb.jpg
v1625329711/IRC_Researchers%20/ashane_djvdkw.jpg
v1625329762/IRC_Researchers%20/charini_gbeyo8.jpg
v1625329770/IRC_Researchers%20/sanjanee_llsq1r.jpg
v1625329799/IRC_Researchers%20/scynthya_wzzx4j.jpg
v1625329809/IRC_Researchers%20/sumudu_wbk63q.jpg
v1625329818/IRC_Researchers%20/madhushibandara_d1ctnp.jpg
v1625329826/IRC_Researchers%20/maneeshaperera_fcezof.jpg
v1625329832/IRC_Researchers%20/udara_j2rw42.jpg
v1625329845/IRC_Researchers%20/sanath_ngtyh9.jpg
v1625329851/IRC_Researchers%20/paranietharan_qtinon.jpg
v1625329855/IRC_Researchers%20/deshya_nnscfv.jpg
v1625329862/IRC_Researchers%20/heshanjayawardane_smyfj0.jpg
v1625329869/IRC_Researchers%20/yudharshini_vafmj4.jpg
v1625329874/IRC_Researchers%20/harshani_c2wqtb.jpg
v1625329878/IRC_Researchers%20/vinuri_a79qcn.jpg
v1625329883/IRC_Researchers%20/kasunbandara_crzc70.jpg
v1625329895/IRC_Researchers%20/ravihansa_sidqsx.jpg
v1625329903/IRC_Researchers%20/malinga_eneaxf.jpg
v1625329909/IRC_Researchers%20/rangana_y2vmxr.jpg
v1625329915/IRC_Researchers%20/amali_yfjhhn.jpg
v1625329921/IRC_Researchers%20/nadundissanayake_oftnse.jpg
v1625329927/IRC_Researchers%20/jerome_ozwjff.jpg
v1625329963/IRC_Researchers%20/chathuranga_hxayxl.jpg
v1625329971/IRC_Researchers%20/asanka_vrgzz8.jpg
v1625329983/IRC_Researchers%20/charitha_rytcmn.jpg
v1625329985/IRC_Researchers%20/sachinthana_zwcyby.jpg
v1625329999/IRC_Researchers%20/sanje_cptzmd.jpg
v1625330008/IRC_Researchers%20/mukunthan_odxsbm.jpg
v1625330015/IRC_Researchers%20/samintha_acxkof.jpg
v1625330019/IRC_Researchers%20/tharinduw_svllyq.jpg
v1625330039/IRC_Researchers%20/saja_aozx9r.jpg
v1625330044/IRC_Researchers%20/jayaruwan_gtpwlb.jpg

```

google sheet link- https://docs.google.com/spreadsheets/d/16tCOj7BfBF0mm61atXhKCohx79DibNZIZb8W7S7HUhM/edit?usp=sharing

2. Replace `assets/img/profiles/{{image}}` with `https://res.cloudinary.com/dsxobn1ln/image/upload/{{image}}` in the irc.html

### PR DESCRIPTION
**Pull request by akeel230**
## Purpose
fix #1002 

## Goals
Use Cloudinary image hosting service to import images to the researcher's section on the IRC page

## Approach

Updated the google sheet  with the URLs in the issue #1002 

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Preview Link
https://pr-1009-sef-site.surge.sh/

### CODE REVIEW

**Review by janethavi — CHANGES_REQUESTED** [review]
Will you be able to add the preview link to the PR template? I think you have removed the Preview Link section

**Comment by akeel230** [comment]
@janethavi sorry my bad , i added the link again, wont happen again. :)

**Review by janethavi — APPROVED** [review]
Great work @akeel230!

**Comment by akeel230** [comment]
@janethavi thanks alot.😃

**Pull request merged**
