### PR TITLE
Add research interns 2020

### LINKED ISSUE #953: Add research interns 2020
**Describe the bug**
The research Interns section is missing in the [IRC page](https://sefglobal.org/irc.html).

**To Reproduce**
1. Go to [https://sefglobal.org/irc.html](https://sefglobal.org/irc.html)
2. Scroll down to `Researchers` section
3. See that Research Interns section is missing

**Expected behavior**
This sections needs to be filled with the data which can be found in the [document](https://docs.google.com/document/d/1ZDZx4cf1ZdUZOjFZu2BiQjoNqTmre6O8XZxWUxEi6Xw/edit?usp=sharing)

### PR DESCRIPTION
**Pull request by janethavi**
## Purpose
This PR adds the missing data in the research interns section.
Fix #953 

### Preview Link
https://pr-954-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by akshika47** [comment]
It is okay to 'park' this on the IRC page for now. But later this can become a separate page but requires further discussion/UX evaluation.

**Comment by Gimhan-minion** [comment]
@janethavi @akshika47 Shall we get this PR merged? Or is it still pending? 😃

**Comment by janethavi** [comment]
If any change needs to be done let me know @akshika47 @Gimhan-minion.

**Review by jayasanka-sack — APPROVED** [review]
Thanks, @janethavi !
Let's get this merged. We had a discussion about improving the IRC page yesterday. Gimhan will post a summary on hive. @Gimhan-minion could you please update Janeth?

**Pull request merged**
