### PR TITLE
fixing Adding gmail icon issue

### LINKED ISSUE #723: Add SEF gmail to the website
**Is your feature request related to a problem? Please describe.**
SEF Gmail is not shown on our website. It should be added

**Describe the solution you'd like**
Add the SEF Gmail (info[AT]sefglobal[DOT]org) on the website. It needs to be obvious for anyone to contact us. Looking for a suggestion on where to place the email address as well.

### PR DESCRIPTION
**Pull request by bhagyesh2000**
## Purpose

The purpose of this PR is to fix #723 

## Goals

Adding sef gmail to the footer

## Approach

Added the gmail icon

### Screenshots

IMG_20200811_181317

  
### Preview Link

https://pr-735-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs

N/A

## Test environment
 
N/A

## Learning

N/A

### CODE REVIEW

**Comment by Gravewalker666** [comment]
Hello @bhagyesh2000 
Good job with the PR. Thank You for contributing.
Anyhow, it would be much easier to understand what and how you have done if you could fill in the details of the PR according to the provided PR template. 
Could you please update your PR with that?
You can find the PR template [here.](https://github.com/sef-global/sef-site/blob/master/pull_request_template.md)

**Comment by Gravewalker666** [comment]
@bhagyesh2000 Are you still working on this mate?

**Comment by Piumal1999** [comment]
I added the missing details on PR description

**Review by Gravewalker666 — APPROVED** [review]
Thanks @Piumal1999

**Review by Gimhan-minion — APPROVED** [review]
Thank you @Piumal1999

**Pull request merged**
