### PR TITLE
Update IRC page with new profiles

### LINKED ISSUE #758: Update IRC researchers list
**Is your feature request related to a problem? Please describe.**
We need to add the new IRC researchers' profiles to the IRC page

**Describe the solution you'd like**
Add the images taken from linkedin profiles.
Update assets/content/json/irc.json file

New profiles:
Name | Position | Field | Linkedin
| -- | -- | -- | -- |
Kasun Bandara | Ph.D Candidate | Data Science | linkedin.com/in/bandarakasun
Ravihansa Rajapakse | Ph.D Candidate | Computer Science (HCI) | linkedin.com/in/ravihansarajapakse
Malinga Perera | Ph.D Candidate | Computer Science | linkedin.com/in/malingaperera
Rangana Shalika | Ph.D | Eco-Tourism | linkedin.com/in/dr-rangana-shalika-77a77179
Amali Shanya Fernando | Ph.D Candidate | Molecular Biology | linkedin.com/in/amali-fernando-944511108
Nadun Dissanayake | Ph.D Candidate | Computational and Applied Mathematics | linkedin.com/in/nadun-dissanayake-46a952a0
Jerome Dinal Herath | Ph.D Candidate | Computer Science | linkedin.com/in/jerome-dinal-herath

**Describe alternatives you've considered**
N/A

**Additional context**
You can refer this thread. https://sef.discourse.group/t/updating-irc-page/171

Or this pull request
https://github.com/sef-global/sef-site/pull/743

### PR DESCRIPTION
**Pull request by janethavi**
## Purpose
Add new IRC profiles.
The purpose of this PR is to fix #758 

## Goals
New research profiles are added. 

## Approach
Added the linked in profile pictures to the asserts.
Update the irc json file with new profiles

### Screenshots
Screenshot from 2020-09-02 19-12-34

  
### Preview Link
https://pr-767-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
-Ubuntu 18.04, Google Chrome

### CODE REVIEW

**Comment by akshika47** [comment]
@janethavi you might want to get a better image of Ravihansa. His image has a sticker on it.

**Comment by janethavi** [comment]
Screenshot from 2020-09-02 20-50-59
@akshika47 I Updated ravihansa's photo

**Comment by akshika47** [comment]
Thank you @janethavi , Clearly, these issues are getting easier for you looking at the speed that you are completing them. I think it is time to level up. Check issues in the ScholarX repo (https://github.com/sef-global/scholarx/issues)! I think they might be of interest to you.

**Review by akshika47 — APPROVED** [review]

**Review by Piumal1999 — APPROVED** [review]

**Comment by Piumal1999** [comment]
Thank you @janethavi !!!

**Pull request merged**
