### PR TITLE
Replace ScholarX 2021 mentor's images with Cloudinary URLs 

### LINKED ISSUE #1036: Replace ScholarX 2021 mentor's images with Cloudinary URLs
**Is your feature request related to a problem? Please describe.**
Use Cloudinary image hosting service to import images to the page

**Describe the solution you'd like**
1. Use the below image URLs to update the image column in the google sheet
 ```
v1625395668/ScholarX_Mentors/2021/malsha_mdxhlq.jpg
v1625395668/ScholarX_Mentors/2021/yadurshini_jhaosc.jpg
v1625395667/ScholarX_Mentors/2021/seyon_ptysdf.jpg
v1625395667/ScholarX_Mentors/2021/vinoj_xaokjy.jpg
v1625395667/ScholarX_Mentors/2021/yomani_k5684g.jpg
v1625395666/ScholarX_Mentors/2021/Pramodh_Yapa_pxxpen.png
v1625395666/ScholarX_Mentors/2021/thisum_tjjicl.jpg
v1625395666/ScholarX_Mentors/2021/vasuki_q4vwzj.jpg
v1625395666/ScholarX_Mentors/2021/sumali_g0r4md.jpg
v1625395665/ScholarX_Mentors/2021/shalini_x5goot.jpg
v1625395664/ScholarX_Mentors/2021/sanath_dlxzw0.jpg
v1625395664/ScholarX_Mentors/2021/sunanda_arfqyd.jpg
v1625395664/ScholarX_Mentors/2021/sumudu_rlahyq.jpg
v1625395663/ScholarX_Mentors/2021/sajani_c33qem.jpg
v1625395663/ScholarX_Mentors/2021/stennakoon_vflkyv.jpg
v1625395663/ScholarX_Mentors/2021/priyadharshany_bdvqeb.jpg
v1625395662/ScholarX_Mentors/2021/ruwini_x5j8pm.jpg
v1625395662/ScholarX_Mentors/2021/rukshan_igqed6.jpg
v1625395661/ScholarX_Mentors/2021/ranin_fbxm7t.jpg
v1625395661/ScholarX_Mentors/2021/ruwandi_xggor2.jpg
v1625395660/ScholarX_Mentors/2021/sajith_bwiqsa.jpg
v1625395660/ScholarX_Mentors/2021/sadeep_ac7fcp.jpg
v1625395660/ScholarX_Mentors/2021/malinda_euwp9o.jpg
v1625395659/ScholarX_Mentors/2021/mirantha_xcg5wu.png
v1625395659/ScholarX_Mentors/2021/pramodh_sdheug.jpg
v1625395658/ScholarX_Mentors/2021/mukunthan_t1kn6q.jpg
v1625395658/ScholarX_Mentors/2021/niwanthika_s7bou5.jpg
v1625395658/ScholarX_Mentors/2021/nilu_j4vj23.jpg
v1625395658/ScholarX_Mentors/2021/mahendrini_av7g6i.jpg
v1625395658/ScholarX_Mentors/2021/lakmin_snnddi.jpg
v1625395658/ScholarX_Mentors/2021/nishantha_nflj2l.jpg
v1625395658/ScholarX_Mentors/2021/navodinee_dw7cek.jpg
v1625395657/ScholarX_Mentors/2021/nadeesha_jmtbl5.jpg
v1625395657/ScholarX_Mentors/2021/lahiru_b9oouu.jpg
v1625395657/ScholarX_Mentors/2021/lakmal_inkgzj.jpg
v1625395656/ScholarX_Mentors/2021/chamode_lbiqeo.jpg
v1625395656/ScholarX_Mentors/2021/gamalendira_ltcdou.png
v1625395656/ScholarX_Mentors/2021/hasini_b6aoy5.jpg
v1625395656/ScholarX_Mentors/2021/kasun_gfetrq.jpg
v1625395656/ScholarX_Mentors/2021/isuru_w8g7zj.jpg
v1625395654/ScholarX_Mentors/2021/hiroshan_x7kryu.jpg
v1625395654/ScholarX_Mentors/2021/ishan_aarfyz.jpg
v1625395654/ScholarX_Mentors/2021/jeewika_lgkihx.jpg
v1625395654/ScholarX_Mentors/2021/jayeni_mhz6om.jpg
v1625395653/ScholarX_Mentors/2021/jathushan_rqfzyi.jpg
v1625395653/ScholarX_Mentors/2021/iromi_tje3if.jpg
v1625395652/ScholarX_Mentors/2021/charuni_djigal.jpg
v1625395652/ScholarX_Mentors/2021/erandathie_jiykp4.jpg
v1625395651/ScholarX_Mentors/2021/hasitha_xfsvgq.jpg
v1625395651/ScholarX_Mentors/2021/anupiya_zlin4i.jpg
v1625395651/ScholarX_Mentors/2021/dulshani_yzhpqn.jpg
v1625395651/ScholarX_Mentors/2021/ajani_vxkqv5.jpg
v1625395651/ScholarX_Mentors/2021/ganindu_ykoqot.jpg
v1625395650/ScholarX_Mentors/2021/gihan_ikijk8.jpg
v1625395650/ScholarX_Mentors/2021/durga_acljtn.jpg
v1625395648/ScholarX_Mentors/2021/asara_modja4.jpg
v1625395648/ScholarX_Mentors/2021/dinuka_rm1til.jpg
v1625395647/ScholarX_Mentors/2021/deepesh_peufnc.jpg
v1625395647/ScholarX_Mentors/2021/dinithi_gix6us.jpg
v1625395646/ScholarX_Mentors/2021/chethiya_wdgvqq.jpg
v1625395645/ScholarX_Mentors/2021/chathura_uhiru2.jpg
v1625395645/ScholarX_Mentors/2021/arosha_bv5aof.jpg
v1625395645/ScholarX_Mentors/2021/athif_epbzcp.jpg
v1625395644/ScholarX_Mentors/2021/awanthika_f8x8p8.jpg
v1625395644/ScholarX_Mentors/2021/aftab_z5yl1c.jpg
v1626870518/ScholarX_Mentors/2021/Kasun_bvbee7.jpg
v1626870515/ScholarX_Mentors/2021/vishvapali_pfqfzm.jpg
v1626870515/ScholarX_Mentors/2021/Nadeeja_s1j1qq.jpg
v1626870514/ScholarX_Mentors/2021/Ashane_p95uyf.jpg
v1626870514/ScholarX_Mentors/2021/Keshab_vufbqd.jpg
v1626870513/ScholarX_Mentors/2021/Pushpi_mgojm2.jpg
v1626870513/ScholarX_Mentors/2021/Akila_fnheef.jpg
v1626870514/ScholarX_Mentors/2021/Rukshani_v4tsya.jpg
v1626870512/ScholarX_Mentors/2021/Buddhima_srv6ki.jpg
v1626870512/ScholarX_Mentors/2021/Charith_g0by0u.png
v1626870512/ScholarX_Mentors/2021/Hasini_duwvwp.jpg
v1626870512/ScholarX_Mentors/2021/Hasitha_d52mvd.jpg
```
google sheet link- 
https://docs.google.com/spreadsheets/d/17v6VOakEMPAjVKKXjUsz7mcPXX-wBGdSqBLnBBLG_tU/edit?usp=sharing

2. Replace `images/{{image}}` with `https://res.cloudinary.com/dsxobn1ln/image/upload/c_scale,h_150,w_150/{{image}}` in the scholarx/2021/index.html

### PR DESCRIPTION
**Pull request by akeel230**
## Purpose
fix  #1036

## Goals
Replace ScholarX 2021 mentor's images with Cloudinary URLs 

## Approach
Copy image URLs in issue #1036  to spreadsheet and update link in index.html

### Screenshots
Screenshot (193)

  
### Preview Link

https://pr-1042-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
#1041

### CODE REVIEW

**Review by Gravewalker666 — COMMENTED** [review]
@gajindubandara @akeel230 Dr Sumudu Thennakoon profile image is missing, could you check on that, please??
 
image

**Comment by gajindubandara** [comment]
> @gajindubandara @akeel230 Dr Sumudu Thennakoon profile image is missing, could you check on that, please??
> 
> image

It's fixed now!
image

**Comment by akeel230** [comment]
@Gravewalker666 its done. Thanks for pointing it out.

**Review by Gravewalker666 — COMMENTED** [review]
Let's change the commit message to what you have in the PR title 😊

**Comment by akeel230** [comment]
@Gravewalker666 done. Please take a look

**Review by Gravewalker666 — APPROVED** [review]

**Pull request merged**
