### PR TITLE
Make the background color of the both sections one color in OneLive

### LINKED ISSUE #1323: Make the background color of the both sections one color in OneLive
**Is your feature request related to a problem? Please describe.**
Now, the background color of the `Be a OneLive speaker` and `Recommend a speaker` is different.

**Describe the solution you'd like**
Make the background color of the two sections to white color

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #1323 

## Goals

Making the background color of the both sections one color in OneLive

## Approach

Made the background color of the both sections one color in OneLive

### Screenshots

image

  
### Preview Link

https://pr-1341-sef-site.surge.sh/onelive

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
@Piumal1999 can you review this?

**Comment by YoshithaRathnayake** [comment]
@anjula-sack

**Comment by anjula-sack** [comment]
Thank you! @YoshithaRathnayake but I think we should keep this. It helps to differentiate the two sections. @Piumal1999 @Madhawa97 What do you think?

**Comment by Madhawa97** [comment]
I agree with you @anjula-sack. Looks better with the different colors.

**Comment by anjula-sack** [comment]
Shall we close this? @YoshithaRathnayake I think we need that bg colors.

**Comment by YoshithaRathnayake** [comment]
> Shall we close this? @YoshithaRathnayake I think we need that bg colors.

Sure @anjula-sack, can you assign me for other issues

**Pull request closed without merging**
