### PR TITLE
Move scholarx success stories folder inside the scholax folder

### LINKED ISSUE #1275: Move scholarx success stories folder inside the scholax folder
**Is your feature request related to a problem? Please describe.**
The scholax `success-stories` folder should be inside of the scholax folder so that the url will be displayed as `https://sefglobal.org/scholarx/success-stories/`

**Describe the solution you'd like**
move the `succes-stories` folder from root to the `scholarx` folder. and update the access url on the `scholarx 2022` page

**Are you working on it?**
No. (I will invite a friend, Actually)

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #1275 

## Goals

Moving scholarx success stories folder inside the scholax folder

## Approach

Moved scholarx success stories folder inside the scholax folder

### Screenshots

No screenshots
  
### Preview Link

https://pr-1279-sef-site.surge.sh/scholarx/2022

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by anjula-sack** [comment]
@YoshithaRathnayake can you fix the conflicts?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake can you fix the conflicts?

@anjula-sack the button resolve conflicts seems to be disable bcs I can't click that

**Comment by anjula-sack** [comment]
> > @YoshithaRathnayake can you fix the conflicts?
> 
> @anjula-sack the button resolve conflicts seems to be disable bcs I can't click that

you can resolve them locally.

Refer to this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

**Comment by YoshithaRathnayake** [comment]
Ok I couldn't resolve the conflicts so I will close this pr and open another one

**Pull request closed without merging**
